"""Error codes for API responses."""

from enum import Enum


class AuthErrorCode(str, Enum):
    """Authentication and authorization error codes."""

    # Credentials
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_PASSWORD = "INVALID_PASSWORD"

    # Account state
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    USER_NOT_FOUND = "USER_NOT_FOUND"

    # Token/session
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND"
    REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED"

    # Email verification
    EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
    VERIFICATION_TOKEN_INVALID = "VERIFICATION_TOKEN_INVALID"
    VERIFICATION_TOKEN_EXPIRED = "VERIFICATION_TOKEN_EXPIRED"

    # Password reset
    RESET_TOKEN_INVALID = "RESET_TOKEN_INVALID"
    RESET_TOKEN_EXPIRED = "RESET_TOKEN_EXPIRED"
    PASSWORD_INCORRECT = "PASSWORD_INCORRECT"

    # 2FA
    TWO_FACTOR_REQUIRED = "TWO_FACTOR_REQUIRED"
    TWO_FACTOR_SETUP_REQUIRED = "TWO_FACTOR_SETUP_REQUIRED"
    TWO_FACTOR_CODE_INVALID = "TWO_FACTOR_CODE_INVALID"
    TWO_FACTOR_NOT_ENABLED = "TWO_FACTOR_NOT_ENABLED"

    # OAuth
    OAUTH_PROVIDER_NOT_CONFIGURED = "OAUTH_PROVIDER_NOT_CONFIGURED"
    OAUTH_STATE_INVALID = "OAUTH_STATE_INVALID"
    OAUTH_PROVIDER_MISMATCH = "OAUTH_PROVIDER_MISMATCH"
    OAUTH_CALLBACK_FAILED = "OAUTH_CALLBACK_FAILED"
    OAUTH_LINK_FAILED = "OAUTH_LINK_FAILED"
    OAUTH_REAUTHENTICATION_REQUIRED = "OAUTH_REAUTHENTICATION_REQUIRED"

    # Generic
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    VALIDATION_ERROR = "VALIDATION_ERROR"
