"""Add iteration and verdict fields to AgentRun model

Revision ID: a3fd7b821b30
Revises: 6c4d5e6f7g8h
Create Date: 2025-12-28 09:55:18.150629

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3fd7b821b30"
down_revision: str | None = "6c4d5e6f7g8h"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_runs", sa.Column("iteration", sa.Integer(), nullable=False, server_default="1")
    )
    op.add_column("agent_runs", sa.Column("verdict", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_agent_runs_iteration"), "agent_runs", ["iteration"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_runs_iteration"), table_name="agent_runs")
    op.drop_column("agent_runs", "verdict")
    op.drop_column("agent_runs", "iteration")
    # ### end Alembic commands ###
