// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const;

export const TaskCreateSchema = {
  properties: {
    title: {
      type: 'string',
      maxLength: 255,
      minLength: 1,
      title: 'Title',
    },
    description: {
      type: 'string',
      minLength: 1,
      title: 'Description',
    },
    priority: {
      $ref: '#/components/schemas/TaskPriority',
      default: 'medium',
    },
    repository_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Repository Id',
    },
  },
  type: 'object',
  required: ['title', 'description'],
  title: 'TaskCreate',
  description: 'Schema for creating a new task.',
} as const;

export const TaskListResponseSchema = {
  properties: {
    items: {
      items: {
        $ref: '#/components/schemas/TaskResponse',
      },
      type: 'array',
      title: 'Items',
    },
    total: {
      type: 'integer',
      title: 'Total',
    },
    page: {
      type: 'integer',
      title: 'Page',
    },
    page_size: {
      type: 'integer',
      title: 'Page Size',
    },
  },
  type: 'object',
  required: ['items', 'total', 'page', 'page_size'],
  title: 'TaskListResponse',
  description: 'Schema for paginated task list responses.',
} as const;

export const TaskPrioritySchema = {
  type: 'string',
  enum: ['low', 'medium', 'high', 'urgent'],
  title: 'TaskPriority',
  description: 'Enum representing the priority of a task.',
} as const;

export const TaskResponseSchema = {
  properties: {
    title: {
      type: 'string',
      maxLength: 255,
      minLength: 1,
      title: 'Title',
    },
    description: {
      type: 'string',
      minLength: 1,
      title: 'Description',
    },
    priority: {
      $ref: '#/components/schemas/TaskPriority',
      default: 'medium',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    status: {
      $ref: '#/components/schemas/TaskStatus',
    },
    user_id: {
      type: 'integer',
      title: 'User Id',
    },
    repository_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Repository Id',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
  },
  type: 'object',
  required: [
    'title',
    'description',
    'id',
    'status',
    'user_id',
    'repository_id',
    'created_at',
    'updated_at',
  ],
  title: 'TaskResponse',
  description: 'Schema for task responses.',
} as const;

export const TaskStatusSchema = {
  type: 'string',
  enum: [
    'pending',
    'planning',
    'in_progress',
    'testing',
    'reviewing',
    'completed',
    'failed',
    'cancelled',
  ],
  title: 'TaskStatus',
  description: 'Enum representing the status of a task.',
} as const;

export const TaskUpdateSchema = {
  properties: {
    title: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255,
          minLength: 1,
        },
        {
          type: 'null',
        },
      ],
      title: 'Title',
    },
    description: {
      anyOf: [
        {
          type: 'string',
          minLength: 1,
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    status: {
      anyOf: [
        {
          $ref: '#/components/schemas/TaskStatus',
        },
        {
          type: 'null',
        },
      ],
    },
    priority: {
      anyOf: [
        {
          $ref: '#/components/schemas/TaskPriority',
        },
        {
          type: 'null',
        },
      ],
    },
    repository_id: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Repository Id',
    },
  },
  type: 'object',
  title: 'TaskUpdate',
  description: 'Schema for updating a task.',
} as const;

export const TokenResponseSchema = {
  properties: {
    access_token: {
      type: 'string',
      title: 'Access Token',
    },
    refresh_token: {
      type: 'string',
      title: 'Refresh Token',
    },
    token_type: {
      type: 'string',
      title: 'Token Type',
      default: 'bearer',
    },
  },
  type: 'object',
  required: ['access_token', 'refresh_token'],
  title: 'TokenResponse',
  description: 'Schema for authentication token response.',
} as const;

export const UserCreateSchema = {
  properties: {
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    password: {
      type: 'string',
      minLength: 8,
      title: 'Password',
      description: 'User password (minimum 8 characters)',
    },
  },
  type: 'object',
  required: ['email', 'password'],
  title: 'UserCreate',
  description: 'Schema for creating a new user.',
} as const;

export const UserLoginSchema = {
  properties: {
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    password: {
      type: 'string',
      title: 'Password',
    },
  },
  type: 'object',
  required: ['email', 'password'],
  title: 'UserLogin',
  description: 'Schema for user login.',
} as const;

export const UserResponseSchema = {
  properties: {
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
    },
    is_superuser: {
      type: 'boolean',
      title: 'Is Superuser',
    },
    created_at: {
      type: 'string',
      format: 'date-time',
      title: 'Created At',
    },
    updated_at: {
      type: 'string',
      format: 'date-time',
      title: 'Updated At',
    },
  },
  type: 'object',
  required: ['email', 'id', 'is_active', 'is_superuser', 'created_at', 'updated_at'],
  title: 'UserResponse',
  description: 'Schema for user responses.',
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const;
