// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AssignUserRoleApiV1AdminUsersUserIdRolePostData,
  AssignUserRoleApiV1AdminUsersUserIdRolePostErrors,
  AssignUserRoleApiV1AdminUsersUserIdRolePostResponses,
  CancelTaskApiV1TasksTaskIdCancelPostData,
  CancelTaskApiV1TasksTaskIdCancelPostErrors,
  CancelTaskApiV1TasksTaskIdCancelPostResponses,
  ChangeEmailApiV1AuthChangeEmailPostData,
  ChangeEmailApiV1AuthChangeEmailPostErrors,
  ChangeEmailApiV1AuthChangeEmailPostResponses,
  ChangePasswordApiV1AuthChangePasswordPostData,
  ChangePasswordApiV1AuthChangePasswordPostErrors,
  ChangePasswordApiV1AuthChangePasswordPostResponses,
  CreateTaskApiV1TasksPostData,
  CreateTaskApiV1TasksPostErrors,
  CreateTaskApiV1TasksPostResponses,
  CreateWebhookApiV1WebhooksPostData,
  CreateWebhookApiV1WebhooksPostErrors,
  CreateWebhookApiV1WebhooksPostResponses,
  DeleteTaskApiV1TasksTaskIdDeleteData,
  DeleteTaskApiV1TasksTaskIdDeleteErrors,
  DeleteTaskApiV1TasksTaskIdDeleteResponses,
  DeleteWebhookApiV1WebhooksWebhookIdDeleteData,
  DeleteWebhookApiV1WebhooksWebhookIdDeleteErrors,
  DeleteWebhookApiV1WebhooksWebhookIdDeleteResponses,
  DisableTwoFactorApiV1TwoFactorDisablePostData,
  DisableTwoFactorApiV1TwoFactorDisablePostErrors,
  DisableTwoFactorApiV1TwoFactorDisablePostResponses,
  EnableTwoFactorApiV1TwoFactorEnablePostData,
  EnableTwoFactorApiV1TwoFactorEnablePostErrors,
  EnableTwoFactorApiV1TwoFactorEnablePostResponses,
  EstimateMonthlyCostApiV1MetricsEstimatePostData,
  EstimateMonthlyCostApiV1MetricsEstimatePostErrors,
  EstimateMonthlyCostApiV1MetricsEstimatePostResponses,
  ExecuteTaskStreamApiV1TasksTaskIdExecutePostData,
  ExecuteTaskStreamApiV1TasksTaskIdExecutePostErrors,
  ExecuteTaskStreamApiV1TasksTaskIdExecutePostResponses,
  ForgotPasswordApiV1AuthForgotPasswordPostData,
  ForgotPasswordApiV1AuthForgotPasswordPostErrors,
  ForgotPasswordApiV1AuthForgotPasswordPostResponses,
  GetAgentMetricsApiV1MetricsAgentAgentTypeGetData,
  GetAgentMetricsApiV1MetricsAgentAgentTypeGetErrors,
  GetAgentMetricsApiV1MetricsAgentAgentTypeGetResponses,
  GetConnectedAccountsOauthAccountsGetData,
  GetConnectedAccountsOauthAccountsGetErrors,
  GetConnectedAccountsOauthAccountsGetResponses,
  GetCouncilMetricsApiV1CouncilMetricsGetData,
  GetCouncilMetricsApiV1CouncilMetricsGetErrors,
  GetCouncilMetricsApiV1CouncilMetricsGetResponses,
  GetCurrentUserInfoApiV1AuthMeGetData,
  GetCurrentUserInfoApiV1AuthMeGetErrors,
  GetCurrentUserInfoApiV1AuthMeGetResponses,
  GetCurrentUserInfoApiV1UsersMeGetData,
  GetCurrentUserInfoApiV1UsersMeGetErrors,
  GetCurrentUserInfoApiV1UsersMeGetResponses,
  GetExecutionTimelineApiV1TasksTaskIdTimelineGetData,
  GetExecutionTimelineApiV1TasksTaskIdTimelineGetErrors,
  GetExecutionTimelineApiV1TasksTaskIdTimelineGetResponses,
  GetGlobalMetricsApiV1MetricsGlobalGetData,
  GetGlobalMetricsApiV1MetricsGlobalGetErrors,
  GetGlobalMetricsApiV1MetricsGlobalGetResponses,
  GetMetricsHistoryApiV1MetricsHistoryGetData,
  GetMetricsHistoryApiV1MetricsHistoryGetErrors,
  GetMetricsHistoryApiV1MetricsHistoryGetResponses,
  GetMetricsSummaryApiV1MetricsSummaryGetData,
  GetMetricsSummaryApiV1MetricsSummaryGetErrors,
  GetMetricsSummaryApiV1MetricsSummaryGetResponses,
  GetOauthProvidersOauthProvidersGetData,
  GetOauthProvidersOauthProvidersGetResponses,
  GetPricingInfoApiV1MetricsPricingGetData,
  GetPricingInfoApiV1MetricsPricingGetErrors,
  GetPricingInfoApiV1MetricsPricingGetResponses,
  GetRoleApiV1AdminRolesRoleIdGetData,
  GetRoleApiV1AdminRolesRoleIdGetErrors,
  GetRoleApiV1AdminRolesRoleIdGetResponses,
  GetTaskApiV1TasksTaskIdGetData,
  GetTaskApiV1TasksTaskIdGetErrors,
  GetTaskApiV1TasksTaskIdGetResponses,
  GetTaskCouncilReviewsApiV1TasksTaskIdCouncilReviewsGetData,
  GetTaskCouncilReviewsApiV1TasksTaskIdCouncilReviewsGetErrors,
  GetTaskCouncilReviewsApiV1TasksTaskIdCouncilReviewsGetResponses,
  GetTaskHistoryApiV1TasksTaskIdHistoryGetData,
  GetTaskHistoryApiV1TasksTaskIdHistoryGetErrors,
  GetTaskHistoryApiV1TasksTaskIdHistoryGetResponses,
  GetTaskMetricsApiV1MetricsTasksTaskIdGetData,
  GetTaskMetricsApiV1MetricsTasksTaskIdGetErrors,
  GetTaskMetricsApiV1MetricsTasksTaskIdGetResponses,
  GetTaskResultApiV1TasksTaskIdResultGetData,
  GetTaskResultApiV1TasksTaskIdResultGetErrors,
  GetTaskResultApiV1TasksTaskIdResultGetResponses,
  GetTaskStatusApiV1TasksTaskIdStatusGetData,
  GetTaskStatusApiV1TasksTaskIdStatusGetErrors,
  GetTaskStatusApiV1TasksTaskIdStatusGetResponses,
  GetTwoFactorStatusApiV1TwoFactorStatusGetData,
  GetTwoFactorStatusApiV1TwoFactorStatusGetErrors,
  GetTwoFactorStatusApiV1TwoFactorStatusGetResponses,
  GetUserCouncilReviewsApiV1CouncilReviewsGetData,
  GetUserCouncilReviewsApiV1CouncilReviewsGetErrors,
  GetUserCouncilReviewsApiV1CouncilReviewsGetResponses,
  GetUserExecutionHistoryApiV1HistoryGetData,
  GetUserExecutionHistoryApiV1HistoryGetErrors,
  GetUserExecutionHistoryApiV1HistoryGetResponses,
  GetUserPermissionsApiV1AdminUsersUserIdPermissionsGetData,
  GetUserPermissionsApiV1AdminUsersUserIdPermissionsGetErrors,
  GetUserPermissionsApiV1AdminUsersUserIdPermissionsGetResponses,
  GetWebhookApiV1WebhooksWebhookIdGetData,
  GetWebhookApiV1WebhooksWebhookIdGetErrors,
  GetWebhookApiV1WebhooksWebhookIdGetResponses,
  GetWebhookDeliveryApiV1WebhooksWebhookIdDeliveriesDeliveryIdGetData,
  GetWebhookDeliveryApiV1WebhooksWebhookIdDeliveriesDeliveryIdGetErrors,
  GetWebhookDeliveryApiV1WebhooksWebhookIdDeliveriesDeliveryIdGetResponses,
  HealthCheckHealthGetData,
  HealthCheckHealthGetResponses,
  ListPermissionsApiV1AdminPermissionsGetData,
  ListPermissionsApiV1AdminPermissionsGetErrors,
  ListPermissionsApiV1AdminPermissionsGetResponses,
  ListRolesApiV1AdminRolesGetData,
  ListRolesApiV1AdminRolesGetErrors,
  ListRolesApiV1AdminRolesGetResponses,
  ListTasksApiV1TasksGetData,
  ListTasksApiV1TasksGetErrors,
  ListTasksApiV1TasksGetResponses,
  ListUsersWithRolesApiV1AdminUsersGetData,
  ListUsersWithRolesApiV1AdminUsersGetErrors,
  ListUsersWithRolesApiV1AdminUsersGetResponses,
  ListWebhookDeliveriesApiV1WebhooksWebhookIdDeliveriesGetData,
  ListWebhookDeliveriesApiV1WebhooksWebhookIdDeliveriesGetErrors,
  ListWebhookDeliveriesApiV1WebhooksWebhookIdDeliveriesGetResponses,
  ListWebhooksApiV1WebhooksGetData,
  ListWebhooksApiV1WebhooksGetErrors,
  ListWebhooksApiV1WebhooksGetResponses,
  LoginUserApiV1AuthLoginPostData,
  LoginUserApiV1AuthLoginPostErrors,
  LoginUserApiV1AuthLoginPostResponses,
  LogoutApiV1AuthLogoutPostData,
  LogoutApiV1AuthLogoutPostErrors,
  LogoutApiV1AuthLogoutPostResponses,
  OauthAuthorizeLinkOauthProviderAuthorizeLinkGetData,
  OauthAuthorizeLinkOauthProviderAuthorizeLinkGetErrors,
  OauthAuthorizeLinkOauthProviderAuthorizeLinkGetResponses,
  OauthAuthorizeOauthProviderAuthorizeGetData,
  OauthAuthorizeOauthProviderAuthorizeGetErrors,
  OauthAuthorizeOauthProviderAuthorizeGetResponses,
  OauthCallbackOauthProviderCallbackGetData,
  OauthCallbackOauthProviderCallbackGetErrors,
  OauthCallbackOauthProviderCallbackGetResponses,
  RefreshApiV1AuthRefreshPostData,
  RefreshApiV1AuthRefreshPostErrors,
  RefreshApiV1AuthRefreshPostResponses,
  RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostData,
  RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostErrors,
  RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostResponses,
  RegenerateWebhookSecretApiV1WebhooksWebhookIdRegenerateSecretPostData,
  RegenerateWebhookSecretApiV1WebhooksWebhookIdRegenerateSecretPostErrors,
  RegenerateWebhookSecretApiV1WebhooksWebhookIdRegenerateSecretPostResponses,
  RegisterUserApiV1AuthRegisterPostData,
  RegisterUserApiV1AuthRegisterPostErrors,
  RegisterUserApiV1AuthRegisterPostResponses,
  RemoveUserRoleApiV1AdminUsersUserIdRoleDeleteData,
  RemoveUserRoleApiV1AdminUsersUserIdRoleDeleteErrors,
  RemoveUserRoleApiV1AdminUsersUserIdRoleDeleteResponses,
  ResendVerificationApiV1AuthResendVerificationPostData,
  ResendVerificationApiV1AuthResendVerificationPostErrors,
  ResendVerificationApiV1AuthResendVerificationPostResponses,
  ResetPasswordApiV1AuthResetPasswordPostData,
  ResetPasswordApiV1AuthResetPasswordPostErrors,
  ResetPasswordApiV1AuthResetPasswordPostResponses,
  SendTestEmailApiV1TestSendTestEmailPostData,
  SendTestEmailApiV1TestSendTestEmailPostErrors,
  SendTestEmailApiV1TestSendTestEmailPostResponses,
  SetupTwoFactorApiV1TwoFactorSetupPostData,
  SetupTwoFactorApiV1TwoFactorSetupPostErrors,
  SetupTwoFactorApiV1TwoFactorSetupPostResponses,
  TestWebhookApiV1WebhooksWebhookIdTestPostData,
  TestWebhookApiV1WebhooksWebhookIdTestPostErrors,
  TestWebhookApiV1WebhooksWebhookIdTestPostResponses,
  UnlinkOauthAccountOauthProviderUnlinkDeleteData,
  UnlinkOauthAccountOauthProviderUnlinkDeleteErrors,
  UnlinkOauthAccountOauthProviderUnlinkDeleteResponses,
  UpdateProfileApiV1AuthProfilePutData,
  UpdateProfileApiV1AuthProfilePutErrors,
  UpdateProfileApiV1AuthProfilePutResponses,
  UpdateTaskApiV1TasksTaskIdPatchData,
  UpdateTaskApiV1TasksTaskIdPatchErrors,
  UpdateTaskApiV1TasksTaskIdPatchResponses,
  UpdateWebhookApiV1WebhooksWebhookIdPatchData,
  UpdateWebhookApiV1WebhooksWebhookIdPatchErrors,
  UpdateWebhookApiV1WebhooksWebhookIdPatchResponses,
  VerifyEmailApiV1AuthVerifyEmailPostData,
  VerifyEmailApiV1AuthVerifyEmailPostErrors,
  VerifyEmailApiV1AuthVerifyEmailPostResponses,
  VerifyTwoFactorApiV1TwoFactorVerifyPostData,
  VerifyTwoFactorApiV1TwoFactorVerifyPostErrors,
  VerifyTwoFactorApiV1TwoFactorVerifyPostResponses,
  VerifyTwoFactorLoginApiV1AuthVerify2FaPostData,
  VerifyTwoFactorLoginApiV1AuthVerify2FaPostErrors,
  VerifyTwoFactorLoginApiV1AuthVerify2FaPostResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Health Check
 *
 * Health check endpoint.
 *
 * Returns:
 * Dictionary with status message
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCheckHealthGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options,
  });

/**
 * Register User
 *
 * Register a new user.
 *
 * Args:
 * user_data: User registration data
 * db: Database session
 *
 * Returns:
 * Created user instance
 *
 * Raises:
 * HTTPException: If email already exists
 */
export const registerUserApiV1AuthRegisterPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterUserApiV1AuthRegisterPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RegisterUserApiV1AuthRegisterPostResponses,
    RegisterUserApiV1AuthRegisterPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Login User
 *
 * Authenticate user and return JWT tokens.
 *
 * Args:
 * user_data: User login credentials
 * db: Database session
 *
 * Returns:
 * JWT access and refresh tokens
 *
 * Raises:
 * HTTPException: If credentials are invalid
 */
export const loginUserApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginUserApiV1AuthLoginPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    LoginUserApiV1AuthLoginPostResponses,
    LoginUserApiV1AuthLoginPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Verify Two Factor Login
 *
 * Verify 2FA code during login and issue full tokens.
 *
 * Accepts both partial tokens (traditional 2FA flow) and full tokens (OAuth flow).
 * - Partial token: Used during traditional login's 2FA verification step
 * - Full token: Used during OAuth login where user is already authenticated
 *
 * Args:
 * request_data: Request containing 2FA code and remember_me flag
 * request: FastAPI request object (for IP address)
 * response: FastAPI response object (to set cookies)
 * db: Database session
 * current_user: Current user from partial or full token
 *
 * Returns:
 * LoginResponse: Success message with user data and email verification status
 *
 * Raises:
 * HTTPException: If 2FA code is invalid
 */
export const verifyTwoFactorLoginApiV1AuthVerify2FaPost = <ThrowOnError extends boolean = false>(
  options: Options<VerifyTwoFactorLoginApiV1AuthVerify2FaPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    VerifyTwoFactorLoginApiV1AuthVerify2FaPostResponses,
    VerifyTwoFactorLoginApiV1AuthVerify2FaPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/verify-2fa',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Logout
 *
 * Logout user, clears cookies and revokes refresh token.
 *
 * Works even if access token is expired (uses optional authentication).
 *
 * Args:
 * response: FastAPI response object (to clear cookies)
 * refresh_token: Refresh token from cookie
 * current_user: Current authenticated user (if any)
 * db: Database session
 *
 * Returns:
 * dict: Success message
 */
export const logoutApiV1AuthLogoutPost = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutApiV1AuthLogoutPostData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    LogoutApiV1AuthLogoutPostResponses,
    LogoutApiV1AuthLogoutPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/logout',
    ...options,
  });

/**
 * Refresh
 *
 * Refresh access token using refresh token from cookie.
 *
 * Implements token rotation: issues new refresh token and revokes old one.
 *
 * Args:
 * response: FastAPI response object (to set new cookies)
 * request: FastAPI request object (for IP address)
 * refresh_token: Refresh token from cookie
 * db: Database session
 *
 * Returns:
 * dict: Success message
 *
 * Raises:
 * HTTPException: If refresh token is invalid, expired, or revoked
 */
export const refreshApiV1AuthRefreshPost = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshApiV1AuthRefreshPostData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    RefreshApiV1AuthRefreshPostResponses,
    RefreshApiV1AuthRefreshPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/refresh',
    ...options,
  });

/**
 * Get Current User Info
 *
 * Get current authenticated user information.
 *
 * Args:
 * current_user: Current authenticated user
 *
 * Returns:
 * UserResponse: Current user data
 */
export const getCurrentUserInfoApiV1AuthMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserInfoApiV1AuthMeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetCurrentUserInfoApiV1AuthMeGetResponses,
    GetCurrentUserInfoApiV1AuthMeGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/me',
    ...options,
  });

/**
 * Verify Email
 *
 * Verify user email with verification token.
 *
 * If 2FA is mandatory and not enabled, issues a partial token for 2FA setup.
 *
 * Args:
 * request_data: Email verification token
 * response: FastAPI response object for setting cookies
 * db: Database session
 *
 * Returns:
 * VerifyEmailResponse: Success message and 2FA setup requirement
 *
 * Raises:
 * HTTPException: If token is invalid or expired
 */
export const verifyEmailApiV1AuthVerifyEmailPost = <ThrowOnError extends boolean = false>(
  options: Options<VerifyEmailApiV1AuthVerifyEmailPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    VerifyEmailApiV1AuthVerifyEmailPostResponses,
    VerifyEmailApiV1AuthVerifyEmailPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/verify-email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Resend Verification
 *
 * Resend verification email to user.
 *
 * Args:
 * request_data: User email address
 * db: Database session
 *
 * Returns:
 * dict: Success message
 *
 * Raises:
 * HTTPException: If email not found
 */
export const resendVerificationApiV1AuthResendVerificationPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ResendVerificationApiV1AuthResendVerificationPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ResendVerificationApiV1AuthResendVerificationPostResponses,
    ResendVerificationApiV1AuthResendVerificationPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/resend-verification',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Forgot Password
 *
 * Request password reset for user account.
 *
 * Args:
 * request_data: User email address
 * db: Database session
 *
 * Returns:
 * dict: Success message (always returns success for security)
 */
export const forgotPasswordApiV1AuthForgotPasswordPost = <ThrowOnError extends boolean = false>(
  options: Options<ForgotPasswordApiV1AuthForgotPasswordPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ForgotPasswordApiV1AuthForgotPasswordPostResponses,
    ForgotPasswordApiV1AuthForgotPasswordPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/forgot-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Reset Password
 *
 * Reset user password with reset token.
 *
 * Args:
 * request_data: Reset token and new password
 * db: Database session
 *
 * Returns:
 * dict: Success message
 *
 * Raises:
 * HTTPException: If token is invalid or expired
 */
export const resetPasswordApiV1AuthResetPasswordPost = <ThrowOnError extends boolean = false>(
  options: Options<ResetPasswordApiV1AuthResetPasswordPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ResetPasswordApiV1AuthResetPasswordPostResponses,
    ResetPasswordApiV1AuthResetPasswordPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/reset-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Change Password
 *
 * Change password for authenticated user.
 *
 * Args:
 * request_data: Current password and new password
 * current_user: Current authenticated user
 * db: Database session
 *
 * Returns:
 * dict: Success message
 *
 * Raises:
 * HTTPException: If current password is incorrect
 */
export const changePasswordApiV1AuthChangePasswordPost = <ThrowOnError extends boolean = false>(
  options: Options<ChangePasswordApiV1AuthChangePasswordPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ChangePasswordApiV1AuthChangePasswordPostResponses,
    ChangePasswordApiV1AuthChangePasswordPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/change-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Change Email
 *
 * Request email change for authenticated user.
 *
 * Sends verification email to new address.
 *
 * Args:
 * request_data: New email address and password
 * current_user: Current authenticated user
 * db: Database session
 *
 * Returns:
 * dict: Success message
 *
 * Raises:
 * HTTPException: If password is incorrect or new email already registered
 */
export const changeEmailApiV1AuthChangeEmailPost = <ThrowOnError extends boolean = false>(
  options: Options<ChangeEmailApiV1AuthChangeEmailPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ChangeEmailApiV1AuthChangeEmailPostResponses,
    ChangeEmailApiV1AuthChangeEmailPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/change-email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Profile
 *
 * Update user profile information.
 *
 * Args:
 * profile_data: Profile fields to update
 * current_user: Current authenticated user
 * db: Database session
 *
 * Returns:
 * UserResponse: Updated user data
 *
 * Raises:
 * HTTPException: If update fails
 */
export const updateProfileApiV1AuthProfilePut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateProfileApiV1AuthProfilePutData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateProfileApiV1AuthProfilePutResponses,
    UpdateProfileApiV1AuthProfilePutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/auth/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Current User Info
 *
 * Get current user information.
 *
 * Requires a full access token. Rejects partial tokens (2FA verification step).
 *
 * Args:
 * current_user: Current authenticated user (requires full token)
 *
 * Returns:
 * Current user data
 */
export const getCurrentUserInfoApiV1UsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetCurrentUserInfoApiV1UsersMeGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetCurrentUserInfoApiV1UsersMeGetResponses,
    GetCurrentUserInfoApiV1UsersMeGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/users/me',
    ...options,
  });

/**
 * List Tasks
 *
 * List tasks with pagination.
 *
 * Requires: task:read permission
 *
 * - Admins and superusers see all tasks
 * - Other users see only their own tasks
 *
 * Args:
 * db: Database session
 * current_user: Current authenticated user with task:read permission
 * page: Page number (starts at 1)
 * page_size: Number of items per page
 *
 * Returns:
 * Paginated list of tasks
 */
export const listTasksApiV1TasksGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListTasksApiV1TasksGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListTasksApiV1TasksGetResponses,
    ListTasksApiV1TasksGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tasks',
    ...options,
  });

/**
 * Create Task
 *
 * Create a new coding task.
 *
 * Requires: task:create permission
 *
 * Args:
 * task_data: Task creation data
 * db: Database session
 * current_user: Current authenticated user with task:create permission
 *
 * Returns:
 * Created task instance
 */
export const createTaskApiV1TasksPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTaskApiV1TasksPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateTaskApiV1TasksPostResponses,
    CreateTaskApiV1TasksPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tasks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Task
 *
 * Delete a task.
 *
 * Requires: Ownership of the task, or admin/superuser access
 *
 * Args:
 * task_id: Task ID
 * db: Database session
 * current_user: Current authenticated user (ownership verified by dependency)
 *
 * Raises:
 * HTTPException: If task not found
 */
export const deleteTaskApiV1TasksTaskIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTaskApiV1TasksTaskIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteTaskApiV1TasksTaskIdDeleteResponses,
    DeleteTaskApiV1TasksTaskIdDeleteErrors,
    ThrowOnError
  >({ url: '/api/v1/tasks/{task_id}', ...options });

/**
 * Get Task
 *
 * Get a specific task by ID.
 *
 * Requires: Ownership of the task, or admin/superuser access
 *
 * Args:
 * task_id: Task ID
 * db: Database session
 * current_user: Current authenticated user (ownership verified by dependency)
 *
 * Returns:
 * Task instance
 *
 * Raises:
 * HTTPException: If task not found
 */
export const getTaskApiV1TasksTaskIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTaskApiV1TasksTaskIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTaskApiV1TasksTaskIdGetResponses,
    GetTaskApiV1TasksTaskIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tasks/{task_id}',
    ...options,
  });

/**
 * Update Task
 *
 * Update a task.
 *
 * Requires: Ownership of the task, or admin/superuser access
 *
 * Args:
 * task_id: Task ID
 * task_data: Task update data
 * db: Database session
 * current_user: Current authenticated user (ownership verified by dependency)
 *
 * Returns:
 * Updated task instance
 *
 * Raises:
 * HTTPException: If task not found
 */
export const updateTaskApiV1TasksTaskIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<UpdateTaskApiV1TasksTaskIdPatchData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateTaskApiV1TasksTaskIdPatchResponses,
    UpdateTaskApiV1TasksTaskIdPatchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tasks/{task_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Execute Task Stream
 *
 * Execute a coding task with real-time streaming output.
 *
 * Streams the complete execution of the multi-agent workflow, including
 * real-time updates from planning, coding, testing, and review stages.
 * Uses Server-Sent Events (SSE) for efficient streaming to the client.
 *
 * Args:
 * task_id: ID of the task to execute
 * db: Database session
 * current_user: Authenticated user
 *
 * Returns:
 * StreamingResponse with SSE formatted events
 *
 * Raises:
 * HTTPException: If task not found or user lacks permission
 *
 * Query Parameters:
 * thread_id: Optional thread ID for resuming previous execution
 *
 * Example:
 * GET /api/v1/agents/tasks/123/execute
 *
 * Returns streaming events like:
 * data: {"type": "node_start", "node": "planner"}
 *
 *
 * data: {"type": "token", "content": "Step 1: "}
 *
 *
 * data: {"type": "node_end", "node": "planner", "duration": 2.5}
 *
 *
 *
 * Note:
 * Error recovery is handled automatically by the workflow layer via
 * resilient node wrappers that provide retry logic with exponential backoff.
 */
export const executeTaskStreamApiV1TasksTaskIdExecutePost = <ThrowOnError extends boolean = false>(
  options: Options<ExecuteTaskStreamApiV1TasksTaskIdExecutePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ExecuteTaskStreamApiV1TasksTaskIdExecutePostResponses,
    ExecuteTaskStreamApiV1TasksTaskIdExecutePostErrors,
    ThrowOnError
  >({ url: '/api/v1/tasks/{task_id}/execute', ...options });

/**
 * Get Task Status
 *
 * Get current status of a task execution.
 *
 * Returns the latest execution state including current node, progress,
 * and any errors encountered.
 *
 * Args:
 * task_id: ID of the task
 * db: Database session
 * current_user: Authenticated user
 *
 * Returns:
 * Task status object with current state and progress
 *
 * Raises:
 * HTTPException: If task not found
 */
export const getTaskStatusApiV1TasksTaskIdStatusGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTaskStatusApiV1TasksTaskIdStatusGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTaskStatusApiV1TasksTaskIdStatusGetResponses,
    GetTaskStatusApiV1TasksTaskIdStatusGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tasks/{task_id}/status',
    ...options,
  });

/**
 * Cancel Task
 *
 * Cancel an ongoing task execution.
 *
 * Signals the workflow to stop and cleanup resources. The cancellation
 * is graceful - nodes will complete their current operation before stopping.
 *
 * Args:
 * task_id: ID of the task to cancel
 * db: Database session
 * current_user: Authenticated user
 *
 * Returns:
 * Confirmation with cancellation status
 *
 * Raises:
 * HTTPException: If task not found
 */
export const cancelTaskApiV1TasksTaskIdCancelPost = <ThrowOnError extends boolean = false>(
  options: Options<CancelTaskApiV1TasksTaskIdCancelPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CancelTaskApiV1TasksTaskIdCancelPostResponses,
    CancelTaskApiV1TasksTaskIdCancelPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tasks/{task_id}/cancel',
    ...options,
  });

/**
 * Get Task Result
 *
 * Get final result of completed task execution.
 *
 * Returns the complete output from all workflow stages including plan,
 * generated code, test results, and review feedback.
 *
 * Args:
 * task_id: ID of the completed task
 * db: Database session
 * current_user: Authenticated user
 *
 * Returns:
 * Complete task execution result
 *
 * Raises:
 * HTTPException: If task not found or still executing
 */
export const getTaskResultApiV1TasksTaskIdResultGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTaskResultApiV1TasksTaskIdResultGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTaskResultApiV1TasksTaskIdResultGetResponses,
    GetTaskResultApiV1TasksTaskIdResultGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tasks/{task_id}/result',
    ...options,
  });

/**
 * Get Task History
 *
 * Get complete execution history for a task.
 *
 * Returns a comprehensive view of all agent runs, including timing,
 * tokens, costs, and optionally council review data.
 *
 * Args:
 * task_id: ID of the task
 * include_council: Whether to include council review details (default True)
 * db: Database session
 * current_user: Authenticated user
 *
 * Returns:
 * Complete task execution history with all agent runs and metrics
 *
 * Raises:
 * HTTPException: If task not found or user lacks permission
 */
export const getTaskHistoryApiV1TasksTaskIdHistoryGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTaskHistoryApiV1TasksTaskIdHistoryGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTaskHistoryApiV1TasksTaskIdHistoryGetResponses,
    GetTaskHistoryApiV1TasksTaskIdHistoryGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tasks/{task_id}/history',
    ...options,
  });

/**
 * Get User Execution History
 *
 * Get paginated execution history for the current user.
 *
 * Returns a list of all tasks with their execution summary,
 * supporting filtering by status and date range.
 *
 * Args:
 * page: Page number (1-indexed)
 * page_size: Number of items per page (max 100)
 * status: Optional filter by task status
 * date_from: Optional start date filter
 * date_to: Optional end date filter
 * db: Database session
 * current_user: Authenticated user
 *
 * Returns:
 * Paginated list of task execution summaries
 */
export const getUserExecutionHistoryApiV1HistoryGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserExecutionHistoryApiV1HistoryGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUserExecutionHistoryApiV1HistoryGetResponses,
    GetUserExecutionHistoryApiV1HistoryGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/history',
    ...options,
  });

/**
 * Get Execution Timeline
 *
 * Get detailed execution timeline for visualization.
 *
 * Returns a chronological list of all events during task execution,
 * suitable for timeline visualization in the frontend.
 *
 * Args:
 * task_id: ID of the task
 * db: Database session
 * current_user: Authenticated user
 *
 * Returns:
 * List of timeline events with timestamps and event data
 *
 * Raises:
 * HTTPException: If task not found or user lacks permission
 */
export const getExecutionTimelineApiV1TasksTaskIdTimelineGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetExecutionTimelineApiV1TasksTaskIdTimelineGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetExecutionTimelineApiV1TasksTaskIdTimelineGetResponses,
    GetExecutionTimelineApiV1TasksTaskIdTimelineGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tasks/{task_id}/timeline',
    ...options,
  });

/**
 * Get Task Council Reviews
 *
 * Get council review history for a specific task.
 *
 * Returns paginated list of all council reviews for the task,
 * including verdict, consensus type, and judge count.
 *
 * Args:
 * task_id: ID of the task
 * page: Page number (1-indexed)
 * page_size: Number of items per page (max 100)
 * db: Database session
 * current_user: Authenticated user
 *
 * Returns:
 * Paginated list of council reviews
 *
 * Raises:
 * HTTPException: If task not found or user lacks permission
 */
export const getTaskCouncilReviewsApiV1TasksTaskIdCouncilReviewsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetTaskCouncilReviewsApiV1TasksTaskIdCouncilReviewsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTaskCouncilReviewsApiV1TasksTaskIdCouncilReviewsGetResponses,
    GetTaskCouncilReviewsApiV1TasksTaskIdCouncilReviewsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/tasks/{task_id}/council-reviews',
    ...options,
  });

/**
 * Get User Council Reviews
 *
 * Get all council reviews for the current user's tasks.
 *
 * Returns paginated list of all council reviews across all user's tasks,
 * useful for analytics and history views.
 *
 * Args:
 * page: Page number (1-indexed)
 * page_size: Number of items per page (max 100)
 * db: Database session
 * current_user: Authenticated user
 *
 * Returns:
 * Paginated list of council reviews
 */
export const getUserCouncilReviewsApiV1CouncilReviewsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserCouncilReviewsApiV1CouncilReviewsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetUserCouncilReviewsApiV1CouncilReviewsGetResponses,
    GetUserCouncilReviewsApiV1CouncilReviewsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/council-reviews',
    ...options,
  });

/**
 * Get Council Metrics
 *
 * Get aggregate metrics for council reviews.
 *
 * Returns comprehensive metrics including verdict distribution,
 * consensus breakdown, and per-judge performance statistics.
 *
 * Args:
 * date_from: Optional start date filter
 * date_to: Optional end date filter
 * db: Database session
 * current_user: Authenticated user
 *
 * Returns:
 * Aggregate council review metrics
 */
export const getCouncilMetricsApiV1CouncilMetricsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetCouncilMetricsApiV1CouncilMetricsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetCouncilMetricsApiV1CouncilMetricsGetResponses,
    GetCouncilMetricsApiV1CouncilMetricsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/council-metrics',
    ...options,
  });

/**
 * Get Metrics Summary
 *
 * Get high-level metrics summary for dashboard display.
 *
 * Returns aggregated token usage, cost calculations, and per-agent breakdown
 * for the specified time period.
 *
 * Args:
 * period: Time period (24h, 7d, 30d, or all)
 *
 * Returns:
 * MetricsSummaryResponse with tokens, costs, and breakdowns
 */
export const getMetricsSummaryApiV1MetricsSummaryGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMetricsSummaryApiV1MetricsSummaryGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetMetricsSummaryApiV1MetricsSummaryGetResponses,
    GetMetricsSummaryApiV1MetricsSummaryGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/metrics/summary',
    ...options,
  });

/**
 * Get Task Metrics
 *
 * Get metrics for a specific task.
 *
 * Returns detailed token usage and cost breakdown for a single task,
 * including per-agent metrics.
 *
 * Args:
 * task_id: ID of the task
 *
 * Returns:
 * TaskMetricsResponse with task-specific metrics
 */
export const getTaskMetricsApiV1MetricsTasksTaskIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTaskMetricsApiV1MetricsTasksTaskIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetTaskMetricsApiV1MetricsTasksTaskIdGetResponses,
    GetTaskMetricsApiV1MetricsTasksTaskIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/metrics/tasks/{task_id}',
    ...options,
  });

/**
 * Get Metrics History
 *
 * Get time-series metrics data for charting.
 *
 * Returns bucketed metrics data suitable for time-series charts,
 * with configurable period and interval.
 *
 * Args:
 * period: Time period (24h, 7d, 30d)
 * interval: Bucket interval (1h, 6h, 1d)
 *
 * Returns:
 * MetricsTimeseriesResponse with data points
 */
export const getMetricsHistoryApiV1MetricsHistoryGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMetricsHistoryApiV1MetricsHistoryGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetMetricsHistoryApiV1MetricsHistoryGetResponses,
    GetMetricsHistoryApiV1MetricsHistoryGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/metrics/history',
    ...options,
  });

/**
 * Get Agent Metrics
 *
 * Get metrics for a specific agent type.
 *
 * Returns detailed metrics for a single agent type (planner, coder,
 * tester, or reviewer).
 *
 * Args:
 * agent_type: Type of agent (PLANNER, CODER, TESTER, REVIEWER)
 * period: Time period (24h, 7d, 30d, or all)
 *
 * Returns:
 * AgentMetricsResponse with agent-specific metrics
 */
export const getAgentMetricsApiV1MetricsAgentAgentTypeGet = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentMetricsApiV1MetricsAgentAgentTypeGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetAgentMetricsApiV1MetricsAgentAgentTypeGetResponses,
    GetAgentMetricsApiV1MetricsAgentAgentTypeGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/metrics/agent/{agent_type}',
    ...options,
  });

/**
 * Get Pricing Info
 *
 * Get current LLM pricing information.
 *
 * Returns the pricing per 1M tokens for each supported model,
 * useful for displaying cost context to users.
 *
 * Returns:
 * PricingInfoResponse with model pricing
 */
export const getPricingInfoApiV1MetricsPricingGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetPricingInfoApiV1MetricsPricingGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetPricingInfoApiV1MetricsPricingGetResponses,
    GetPricingInfoApiV1MetricsPricingGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/metrics/pricing',
    ...options,
  });

/**
 * Estimate Monthly Cost
 *
 * Estimate monthly costs based on daily token usage.
 *
 * Calculates what the monthly cost would be if using cloud LLMs
 * instead of local vLLM, based on projected daily usage.
 *
 * Args:
 * request: Daily token estimate and input ratio
 *
 * Returns:
 * MonthlyEstimateResponse with cost projections
 */
export const estimateMonthlyCostApiV1MetricsEstimatePost = <ThrowOnError extends boolean = false>(
  options: Options<EstimateMonthlyCostApiV1MetricsEstimatePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    EstimateMonthlyCostApiV1MetricsEstimatePostResponses,
    EstimateMonthlyCostApiV1MetricsEstimatePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/metrics/estimate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Global Metrics
 *
 * Get global metrics across all tasks and users.
 *
 * Returns aggregated metrics for the entire system (admin view).
 * Note: Currently returns user-scoped metrics for security.
 *
 * Args:
 * period: Time period (24h, 7d, 30d, or all)
 *
 * Returns:
 * PeriodMetricsResponse with global metrics
 */
export const getGlobalMetricsApiV1MetricsGlobalGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetGlobalMetricsApiV1MetricsGlobalGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetGlobalMetricsApiV1MetricsGlobalGetResponses,
    GetGlobalMetricsApiV1MetricsGlobalGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/metrics/global',
    ...options,
  });

/**
 * Get Two Factor Status
 *
 * Get the current 2FA status for the authenticated user.
 *
 * Accepts both full and partial tokens (partial tokens during OAuth/2FA flows).
 *
 * Returns:
 * TwoFactorStatusResponse with enabled status and remaining backup codes.
 */
export const getTwoFactorStatusApiV1TwoFactorStatusGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTwoFactorStatusApiV1TwoFactorStatusGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetTwoFactorStatusApiV1TwoFactorStatusGetResponses,
    GetTwoFactorStatusApiV1TwoFactorStatusGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/two-factor/status',
    ...options,
  });

/**
 * Setup Two Factor
 *
 * Start the 2FA setup process.
 *
 * Generates a TOTP secret and QR code for the user to scan with their
 * authenticator app.
 *
 * Can be called during login (with partial token) or from settings (with full token).
 *
 * Returns:
 * TwoFactorSetupResponse with QR code and secret.
 *
 * Raises:
 * HTTPException: If 2FA is already enabled.
 */
export const setupTwoFactorApiV1TwoFactorSetupPost = <ThrowOnError extends boolean = false>(
  options?: Options<SetupTwoFactorApiV1TwoFactorSetupPostData, ThrowOnError>
) =>
  (options?.client ?? client).post<
    SetupTwoFactorApiV1TwoFactorSetupPostResponses,
    SetupTwoFactorApiV1TwoFactorSetupPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/two-factor/setup',
    ...options,
  });

/**
 * Enable Two Factor
 *
 * Enable 2FA after verifying the TOTP code.
 *
 * The user must first call /two-factor/setup and scan the QR code before
 * calling this endpoint with the code from their authenticator app.
 *
 * Can be called during login (with partial token) or from settings (with full token).
 *
 * Args:
 * request: Contains the 6-digit TOTP code.
 *
 * Returns:
 * TwoFactorEnableResponse with backup codes.
 *
 * Raises:
 * HTTPException: If the code is invalid or 2FA is not set up.
 */
export const enableTwoFactorApiV1TwoFactorEnablePost = <ThrowOnError extends boolean = false>(
  options: Options<EnableTwoFactorApiV1TwoFactorEnablePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    EnableTwoFactorApiV1TwoFactorEnablePostResponses,
    EnableTwoFactorApiV1TwoFactorEnablePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/two-factor/enable',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Disable Two Factor
 *
 * Disable 2FA for the authenticated user.
 *
 * Requires the user's password for confirmation.
 *
 * Args:
 * request: Contains the user's password.
 *
 * Returns:
 * Success message.
 *
 * Raises:
 * HTTPException: If 2FA is not enabled or password is incorrect.
 */
export const disableTwoFactorApiV1TwoFactorDisablePost = <ThrowOnError extends boolean = false>(
  options: Options<DisableTwoFactorApiV1TwoFactorDisablePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    DisableTwoFactorApiV1TwoFactorDisablePostResponses,
    DisableTwoFactorApiV1TwoFactorDisablePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/two-factor/disable',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Verify Two Factor
 *
 * Verify a 2FA code (TOTP or backup code).
 *
 * Accepts both full and partial tokens (partial tokens during OAuth/login flows).
 * Can be used during login or for sensitive operations after 2FA setup.
 *
 * Args:
 * request: Contains the TOTP or backup code.
 *
 * Returns:
 * TwoFactorVerifyResponse indicating if the code is valid.
 */
export const verifyTwoFactorApiV1TwoFactorVerifyPost = <ThrowOnError extends boolean = false>(
  options: Options<VerifyTwoFactorApiV1TwoFactorVerifyPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    VerifyTwoFactorApiV1TwoFactorVerifyPostResponses,
    VerifyTwoFactorApiV1TwoFactorVerifyPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/two-factor/verify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Regenerate Backup Codes
 *
 * Regenerate backup codes for the authenticated user.
 *
 * This invalidates all existing backup codes and generates new ones.
 * Requires the user's password for confirmation.
 *
 * Args:
 * request: Contains the user's password.
 *
 * Returns:
 * RegenerateBackupCodesResponse with new backup codes.
 *
 * Raises:
 * HTTPException: If 2FA is not enabled or password is incorrect.
 */
export const regenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostResponses,
    RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/two-factor/regenerate-backup-codes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Webhooks
 *
 * List webhooks for the current user.
 *
 * Args:
 * db: Database session
 * current_user: Current authenticated user
 * page: Page number
 * page_size: Items per page
 * status: Optional status filter
 *
 * Returns:
 * Paginated list of webhooks
 */
export const listWebhooksApiV1WebhooksGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListWebhooksApiV1WebhooksGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListWebhooksApiV1WebhooksGetResponses,
    ListWebhooksApiV1WebhooksGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/webhooks',
    ...options,
  });

/**
 * Create Webhook
 *
 * Create a new webhook.
 *
 * The response includes the generated secret which should be stored securely.
 * The secret is only shown once on creation and cannot be retrieved later.
 *
 * Args:
 * webhook_data: Webhook creation data
 * db: Database session
 * current_user: Current authenticated user
 *
 * Returns:
 * Created webhook with secret
 */
export const createWebhookApiV1WebhooksPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateWebhookApiV1WebhooksPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateWebhookApiV1WebhooksPostResponses,
    CreateWebhookApiV1WebhooksPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/webhooks',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Webhook
 *
 * Delete a webhook.
 *
 * Args:
 * webhook_id: Webhook ID
 * db: Database session
 * current_user: Current authenticated user
 *
 * Raises:
 * HTTPException: If webhook not found
 */
export const deleteWebhookApiV1WebhooksWebhookIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWebhookApiV1WebhooksWebhookIdDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteWebhookApiV1WebhooksWebhookIdDeleteResponses,
    DeleteWebhookApiV1WebhooksWebhookIdDeleteErrors,
    ThrowOnError
  >({ url: '/api/v1/webhooks/{webhook_id}', ...options });

/**
 * Get Webhook
 *
 * Get a specific webhook by ID.
 *
 * Args:
 * webhook_id: Webhook ID
 * db: Database session
 * current_user: Current authenticated user
 *
 * Returns:
 * Webhook details
 *
 * Raises:
 * HTTPException: If webhook not found
 */
export const getWebhookApiV1WebhooksWebhookIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetWebhookApiV1WebhooksWebhookIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetWebhookApiV1WebhooksWebhookIdGetResponses,
    GetWebhookApiV1WebhooksWebhookIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/webhooks/{webhook_id}',
    ...options,
  });

/**
 * Update Webhook
 *
 * Update a webhook.
 *
 * Args:
 * webhook_id: Webhook ID
 * webhook_data: Update data
 * db: Database session
 * current_user: Current authenticated user
 *
 * Returns:
 * Updated webhook
 *
 * Raises:
 * HTTPException: If webhook not found
 */
export const updateWebhookApiV1WebhooksWebhookIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWebhookApiV1WebhooksWebhookIdPatchData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    UpdateWebhookApiV1WebhooksWebhookIdPatchResponses,
    UpdateWebhookApiV1WebhooksWebhookIdPatchErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/webhooks/{webhook_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Regenerate Webhook Secret
 *
 * Regenerate the secret for a webhook.
 *
 * The old secret will be invalidated immediately.
 *
 * Args:
 * webhook_id: Webhook ID
 * db: Database session
 * current_user: Current authenticated user
 *
 * Returns:
 * Webhook with new secret
 *
 * Raises:
 * HTTPException: If webhook not found
 */
export const regenerateWebhookSecretApiV1WebhooksWebhookIdRegenerateSecretPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RegenerateWebhookSecretApiV1WebhooksWebhookIdRegenerateSecretPostData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    RegenerateWebhookSecretApiV1WebhooksWebhookIdRegenerateSecretPostResponses,
    RegenerateWebhookSecretApiV1WebhooksWebhookIdRegenerateSecretPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/webhooks/{webhook_id}/regenerate-secret',
    ...options,
  });

/**
 * Test Webhook
 *
 * Send a test event to a webhook.
 *
 * This sends a test payload to verify the webhook endpoint is working.
 *
 * Args:
 * webhook_id: Webhook ID
 * test_data: Test configuration
 * db: Database session
 * current_user: Current authenticated user
 *
 * Returns:
 * Test result with response details
 */
export const testWebhookApiV1WebhooksWebhookIdTestPost = <ThrowOnError extends boolean = false>(
  options: Options<TestWebhookApiV1WebhooksWebhookIdTestPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TestWebhookApiV1WebhooksWebhookIdTestPostResponses,
    TestWebhookApiV1WebhooksWebhookIdTestPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/webhooks/{webhook_id}/test',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List Webhook Deliveries
 *
 * List delivery history for a webhook.
 *
 * Args:
 * webhook_id: Webhook ID
 * db: Database session
 * current_user: Current authenticated user
 * page: Page number
 * page_size: Items per page
 * delivery_status: Optional status filter
 *
 * Returns:
 * Paginated list of deliveries
 *
 * Raises:
 * HTTPException: If webhook not found
 */
export const listWebhookDeliveriesApiV1WebhooksWebhookIdDeliveriesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ListWebhookDeliveriesApiV1WebhooksWebhookIdDeliveriesGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListWebhookDeliveriesApiV1WebhooksWebhookIdDeliveriesGetResponses,
    ListWebhookDeliveriesApiV1WebhooksWebhookIdDeliveriesGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/webhooks/{webhook_id}/deliveries',
    ...options,
  });

/**
 * Get Webhook Delivery
 *
 * Get a specific delivery by ID.
 *
 * Args:
 * webhook_id: Webhook ID
 * delivery_id: Delivery ID
 * db: Database session
 * current_user: Current authenticated user
 *
 * Returns:
 * Delivery details
 *
 * Raises:
 * HTTPException: If webhook or delivery not found
 */
export const getWebhookDeliveryApiV1WebhooksWebhookIdDeliveriesDeliveryIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetWebhookDeliveryApiV1WebhooksWebhookIdDeliveriesDeliveryIdGetData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    GetWebhookDeliveryApiV1WebhooksWebhookIdDeliveriesDeliveryIdGetResponses,
    GetWebhookDeliveryApiV1WebhooksWebhookIdDeliveriesDeliveryIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/webhooks/{webhook_id}/deliveries/{delivery_id}',
    ...options,
  });

/**
 * Get Oauth Providers
 *
 * Get available OAuth providers and their configuration status.
 *
 * Returns:
 * Dictionary of provider names and whether they are configured.
 */
export const getOauthProvidersOauthProvidersGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetOauthProvidersOauthProvidersGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetOauthProvidersOauthProvidersGetResponses,
    unknown,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/oauth/providers',
    ...options,
  });

/**
 * Oauth Authorize
 *
 * Start OAuth authorization flow.
 *
 * Redirects the user to the OAuth provider's authorization page.
 *
 * Args:
 * provider: OAuth provider name (github, google, microsoft).
 * redirect_url: Optional URL to redirect to after successful auth.
 *
 * Returns:
 * Redirect to the OAuth provider.
 *
 * Raises:
 * HTTPException: If provider is not supported or not configured.
 */
export const oauthAuthorizeOauthProviderAuthorizeGet = <ThrowOnError extends boolean = false>(
  options: Options<OauthAuthorizeOauthProviderAuthorizeGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    OauthAuthorizeOauthProviderAuthorizeGetResponses,
    OauthAuthorizeOauthProviderAuthorizeGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/oauth/{provider}/authorize',
    ...options,
  });

/**
 * Oauth Authorize Link
 *
 * Start OAuth authorization flow for linking to existing account.
 *
 * Requires authentication. Links the OAuth account to the current user.
 *
 * Args:
 * provider: OAuth provider name.
 * redirect_url: Optional URL to redirect to after linking.
 *
 * Returns:
 * Redirect to the OAuth provider.
 */
export const oauthAuthorizeLinkOauthProviderAuthorizeLinkGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<OauthAuthorizeLinkOauthProviderAuthorizeLinkGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    OauthAuthorizeLinkOauthProviderAuthorizeLinkGetResponses,
    OauthAuthorizeLinkOauthProviderAuthorizeLinkGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/oauth/{provider}/authorize/link',
    ...options,
  });

/**
 * Oauth Callback
 *
 * Handle OAuth callback.
 *
 * Exchanges the authorization code for tokens and creates/links user account.
 * Then redirects to frontend with success/error status.
 *
 * Args:
 * provider: OAuth provider name.
 * code: Authorization code from OAuth provider.
 * state: CSRF protection state.
 *
 * Returns:
 * Redirect to frontend.
 *
 * Raises:
 * HTTPException: If callback fails.
 */
export const oauthCallbackOauthProviderCallbackGet = <ThrowOnError extends boolean = false>(
  options: Options<OauthCallbackOauthProviderCallbackGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    OauthCallbackOauthProviderCallbackGetResponses,
    OauthCallbackOauthProviderCallbackGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/oauth/{provider}/callback',
    ...options,
  });

/**
 * Get Connected Accounts
 *
 * Get all OAuth accounts linked to the current user.
 *
 * Returns:
 * List of connected OAuth accounts.
 */
export const getConnectedAccountsOauthAccountsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetConnectedAccountsOauthAccountsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    GetConnectedAccountsOauthAccountsGetResponses,
    GetConnectedAccountsOauthAccountsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/oauth/accounts',
    ...options,
  });

/**
 * Unlink Oauth Account
 *
 * Unlink an OAuth account from the current user.
 *
 * Args:
 * provider: OAuth provider to unlink.
 *
 * Returns:
 * Success message.
 *
 * Raises:
 * HTTPException: If unlinking fails.
 */
export const unlinkOauthAccountOauthProviderUnlinkDelete = <ThrowOnError extends boolean = false>(
  options: Options<UnlinkOauthAccountOauthProviderUnlinkDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    UnlinkOauthAccountOauthProviderUnlinkDeleteResponses,
    UnlinkOauthAccountOauthProviderUnlinkDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/oauth/{provider}/unlink',
    ...options,
  });

/**
 * Send Test Email
 *
 * Send a test email to verify SMTP configuration.
 *
 * **Development Only** - Remove this endpoint in production.
 *
 * Args:
 * recipient_email: Email address to send test email to
 * db: Database session
 *
 * Returns:
 * dict: Success message with details
 *
 * Raises:
 * HTTPException: If email sending fails
 */
export const sendTestEmailApiV1TestSendTestEmailPost = <ThrowOnError extends boolean = false>(
  options: Options<SendTestEmailApiV1TestSendTestEmailPostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    SendTestEmailApiV1TestSendTestEmailPostResponses,
    SendTestEmailApiV1TestSendTestEmailPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/test/send-test-email',
    ...options,
  });

/**
 * List Roles
 *
 * List all roles with their permissions.
 *
 * Requires: Admin role or superuser access
 *
 * Returns:
 * List of all roles with permissions
 */
export const listRolesApiV1AdminRolesGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListRolesApiV1AdminRolesGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListRolesApiV1AdminRolesGetResponses,
    ListRolesApiV1AdminRolesGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/admin/roles',
    ...options,
  });

/**
 * Get Role
 *
 * Get a specific role with its permissions.
 *
 * Requires: Admin role or superuser access
 *
 * Args:
 * role_id: Role ID
 *
 * Returns:
 * Role with permissions
 *
 * Raises:
 * HTTPException: If role not found
 */
export const getRoleApiV1AdminRolesRoleIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetRoleApiV1AdminRolesRoleIdGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetRoleApiV1AdminRolesRoleIdGetResponses,
    GetRoleApiV1AdminRolesRoleIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/admin/roles/{role_id}',
    ...options,
  });

/**
 * List Permissions
 *
 * List all available permissions.
 *
 * Requires: Admin role or superuser access
 *
 * Returns:
 * List of all permissions
 */
export const listPermissionsApiV1AdminPermissionsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListPermissionsApiV1AdminPermissionsGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListPermissionsApiV1AdminPermissionsGetResponses,
    ListPermissionsApiV1AdminPermissionsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/admin/permissions',
    ...options,
  });

/**
 * Remove User Role
 *
 * Remove a role from a user.
 *
 * Requires: Admin role or superuser access
 *
 * Args:
 * user_id: User ID to remove role from
 *
 * Raises:
 * HTTPException: If user not found
 */
export const removeUserRoleApiV1AdminUsersUserIdRoleDelete = <ThrowOnError extends boolean = false>(
  options: Options<RemoveUserRoleApiV1AdminUsersUserIdRoleDeleteData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    RemoveUserRoleApiV1AdminUsersUserIdRoleDeleteResponses,
    RemoveUserRoleApiV1AdminUsersUserIdRoleDeleteErrors,
    ThrowOnError
  >({ url: '/api/v1/admin/users/{user_id}/role', ...options });

/**
 * Assign User Role
 *
 * Assign a role to a user.
 *
 * Requires: Admin role or superuser access
 *
 * Args:
 * user_id: User ID to assign role to
 * assignment: Role assignment data containing role_id
 *
 * Returns:
 * Updated user permissions
 *
 * Raises:
 * HTTPException: If user or role not found
 */
export const assignUserRoleApiV1AdminUsersUserIdRolePost = <ThrowOnError extends boolean = false>(
  options: Options<AssignUserRoleApiV1AdminUsersUserIdRolePostData, ThrowOnError>
) =>
  (options.client ?? client).post<
    AssignUserRoleApiV1AdminUsersUserIdRolePostResponses,
    AssignUserRoleApiV1AdminUsersUserIdRolePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/admin/users/{user_id}/role',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get User Permissions
 *
 * Get all permissions for a specific user.
 *
 * Requires: Admin role or superuser access
 *
 * Args:
 * user_id: User ID
 *
 * Returns:
 * User permissions including role and superuser status
 *
 * Raises:
 * HTTPException: If user not found
 */
export const getUserPermissionsApiV1AdminUsersUserIdPermissionsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserPermissionsApiV1AdminUsersUserIdPermissionsGetData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetUserPermissionsApiV1AdminUsersUserIdPermissionsGetResponses,
    GetUserPermissionsApiV1AdminUsersUserIdPermissionsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/admin/users/{user_id}/permissions',
    ...options,
  });

/**
 * List Users With Roles
 *
 * List all users with their roles and permissions.
 *
 * Requires: Admin role or superuser access
 *
 * Returns:
 * List of users with their permissions
 */
export const listUsersWithRolesApiV1AdminUsersGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListUsersWithRolesApiV1AdminUsersGetData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListUsersWithRolesApiV1AdminUsersGetResponses,
    ListUsersWithRolesApiV1AdminUsersGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/api/v1/admin/users',
    ...options,
  });
