// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: 'http://localhost:8000' | (string & {});
};

/**
 * ChangeEmailRequest
 *
 * Request to change email for authenticated user.
 */
export type ChangeEmailRequest = {
  /**
   * New Email
   */
  new_email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * ChangePasswordRequest
 *
 * Request to change password for authenticated user.
 */
export type ChangePasswordRequest = {
  /**
   * Current Password
   */
  current_password: string;
  /**
   * New Password
   */
  new_password: string;
};

/**
 * ConnectedAccountsResponse
 *
 * Response for listing connected accounts.
 */
export type ConnectedAccountsResponse = {
  /**
   * Accounts
   */
  accounts: Array<OAuthAccountResponse>;
};

/**
 * ForgotPasswordRequest
 *
 * Request to initiate password reset.
 */
export type ForgotPasswordRequest = {
  /**
   * Email
   */
  email: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LoginResponse
 *
 * Response for successful login.
 */
export type LoginResponse = {
  /**
   * Message
   */
  message: string;
  user: UserResponse;
  /**
   * Email Verified
   */
  email_verified: boolean;
  /**
   * Requires Two Factor
   */
  requires_two_factor?: boolean;
  /**
   * Two Factor Enabled
   */
  two_factor_enabled?: boolean;
};

/**
 * OAuthAccountResponse
 *
 * Response for a linked OAuth account.
 */
export type OAuthAccountResponse = {
  /**
   * Provider
   */
  provider: string;
  /**
   * Provider User Id
   */
  provider_user_id: string;
  /**
   * Email
   */
  email?: string | null;
  /**
   * Name
   */
  name?: string | null;
  /**
   * Avatar Url
   */
  avatar_url?: string | null;
  /**
   * Connected At
   */
  connected_at: string;
};

/**
 * ProfileUpdateRequest
 *
 * Schema for updating user profile information.
 */
export type ProfileUpdateRequest = {
  /**
   * First Name
   *
   * User's first name
   */
  first_name?: string | null;
  /**
   * Last Name
   *
   * User's last name
   */
  last_name?: string | null;
  /**
   * Display Name
   *
   * User's display name
   */
  display_name?: string | null;
  /**
   * Avatar Url
   *
   * URL to user's profile picture
   */
  avatar_url?: string | null;
};

/**
 * RegenerateBackupCodesRequest
 *
 * Request to regenerate backup codes.
 */
export type RegenerateBackupCodesRequest = {
  /**
   * Password
   */
  password: string;
};

/**
 * RegenerateBackupCodesResponse
 *
 * Response for backup code regeneration.
 */
export type RegenerateBackupCodesResponse = {
  /**
   * Backup Codes
   */
  backup_codes: Array<string>;
};

/**
 * ResetPasswordRequest
 *
 * Request to reset password with token.
 */
export type ResetPasswordRequest = {
  /**
   * Token
   */
  token: string;
  /**
   * Password
   */
  password: string;
};

/**
 * TaskCreate
 *
 * Schema for creating a new task.
 */
export type TaskCreate = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  priority?: TaskPriority;
  /**
   * Repository Id
   */
  repository_id?: number | null;
};

/**
 * TaskListResponse
 *
 * Schema for paginated task list responses.
 */
export type TaskListResponse = {
  /**
   * Items
   */
  items: Array<TaskResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Page Size
   */
  page_size: number;
};

/**
 * TaskPriority
 *
 * Enum representing the priority of a task.
 */
export const TaskPriority = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  URGENT: 'urgent',
} as const;

/**
 * TaskPriority
 *
 * Enum representing the priority of a task.
 */
export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority];

/**
 * TaskResponse
 *
 * Schema for task responses.
 */
export type TaskResponse = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  priority?: TaskPriority;
  /**
   * Id
   */
  id: number;
  status: TaskStatus;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Repository Id
   */
  repository_id: number | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * TaskStatus
 *
 * Enum representing the status of a task.
 */
export const TaskStatus = {
  PENDING: 'pending',
  PLANNING: 'planning',
  IN_PROGRESS: 'in_progress',
  TESTING: 'testing',
  REVIEWING: 'reviewing',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
} as const;

/**
 * TaskStatus
 *
 * Enum representing the status of a task.
 */
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

/**
 * TaskUpdate
 *
 * Schema for updating a task.
 */
export type TaskUpdate = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  status?: TaskStatus | null;
  priority?: TaskPriority | null;
  /**
   * Repository Id
   */
  repository_id?: number | null;
};

/**
 * TokenResponse
 *
 * Schema for authentication token response.
 */
export type TokenResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Refresh Token
   */
  refresh_token: string;
  /**
   * Token Type
   */
  token_type?: string;
};

/**
 * TwoFactorDisableRequest
 *
 * Request to disable 2FA.
 */
export type TwoFactorDisableRequest = {
  /**
   * Password
   */
  password: string;
};

/**
 * TwoFactorEnableRequest
 *
 * Request to enable 2FA.
 */
export type TwoFactorEnableRequest = {
  /**
   * Code
   */
  code: string;
};

/**
 * TwoFactorEnableResponse
 *
 * Response for enabling 2FA.
 */
export type TwoFactorEnableResponse = {
  /**
   * Backup Codes
   */
  backup_codes: Array<string>;
};

/**
 * TwoFactorLoginRequest
 *
 * Request to verify 2FA code during login.
 */
export type TwoFactorLoginRequest = {
  /**
   * Code
   */
  code: string;
  /**
   * Remember Me
   */
  remember_me?: boolean;
};

/**
 * TwoFactorSetupResponse
 *
 * Response for 2FA setup initiation.
 */
export type TwoFactorSetupResponse = {
  /**
   * Qr Code
   */
  qr_code: string;
  /**
   * Secret
   */
  secret: string;
};

/**
 * TwoFactorStatusResponse
 *
 * Response for 2FA status check.
 */
export type TwoFactorStatusResponse = {
  /**
   * Enabled
   */
  enabled: boolean;
  /**
   * Backup Codes Remaining
   */
  backup_codes_remaining?: number | null;
};

/**
 * TwoFactorVerifyRequest
 *
 * Request to verify a 2FA code.
 */
export type TwoFactorVerifyRequest = {
  /**
   * Code
   */
  code: string;
};

/**
 * TwoFactorVerifyResponse
 *
 * Response for 2FA verification.
 */
export type TwoFactorVerifyResponse = {
  /**
   * Valid
   */
  valid: boolean;
};

/**
 * UserCreate
 *
 * Schema for creating a new user.
 */
export type UserCreate = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   *
   * User password (minimum 8 characters)
   */
  password: string;
  /**
   * First Name
   *
   * User's first name
   */
  first_name?: string | null;
  /**
   * Last Name
   *
   * User's last name
   */
  last_name?: string | null;
};

/**
 * UserLogin
 *
 * Schema for user login.
 */
export type UserLogin = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Remember Me
   */
  remember_me?: boolean;
};

/**
 * UserResponse
 *
 * Schema for user responses.
 */
export type UserResponse = {
  /**
   * Email
   */
  email: string;
  /**
   * Id
   */
  id: number;
  /**
   * Is Active
   */
  is_active: boolean;
  /**
   * Is Superuser
   */
  is_superuser: boolean;
  /**
   * Email Verified
   */
  email_verified: boolean;
  /**
   * Two Factor Enabled
   */
  two_factor_enabled: boolean;
  /**
   * First Name
   */
  first_name?: string | null;
  /**
   * Last Name
   */
  last_name?: string | null;
  /**
   * Display Name
   */
  display_name?: string | null;
  /**
   * Avatar Url
   */
  avatar_url?: string | null;
  /**
   * Profile Completed
   */
  profile_completed: boolean;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

/**
 * VerifyEmailRequest
 *
 * Request to verify email with token.
 */
export type VerifyEmailRequest = {
  /**
   * Token
   */
  token: string;
};

/**
 * VerifyEmailResponse
 *
 * Response after email verification.
 */
export type VerifyEmailResponse = {
  /**
   * Message
   */
  message: string;
  /**
   * Requires 2Fa Setup
   */
  requires_2fa_setup?: boolean;
};

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthCheckHealthGetResponses = {
  /**
   * Response Health Check Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthCheckHealthGetResponse =
  HealthCheckHealthGetResponses[keyof HealthCheckHealthGetResponses];

export type RegisterUserApiV1AuthRegisterPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: '/api/v1/auth/register';
};

export type RegisterUserApiV1AuthRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterUserApiV1AuthRegisterPostError =
  RegisterUserApiV1AuthRegisterPostErrors[keyof RegisterUserApiV1AuthRegisterPostErrors];

export type RegisterUserApiV1AuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  201: UserResponse;
};

export type RegisterUserApiV1AuthRegisterPostResponse =
  RegisterUserApiV1AuthRegisterPostResponses[keyof RegisterUserApiV1AuthRegisterPostResponses];

export type LoginUserApiV1AuthLoginPostData = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: '/api/v1/auth/login';
};

export type LoginUserApiV1AuthLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginUserApiV1AuthLoginPostError =
  LoginUserApiV1AuthLoginPostErrors[keyof LoginUserApiV1AuthLoginPostErrors];

export type LoginUserApiV1AuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type LoginUserApiV1AuthLoginPostResponse =
  LoginUserApiV1AuthLoginPostResponses[keyof LoginUserApiV1AuthLoginPostResponses];

export type VerifyTwoFactorLoginApiV1AuthVerify2FaPostData = {
  body: TwoFactorLoginRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/verify-2fa';
};

export type VerifyTwoFactorLoginApiV1AuthVerify2FaPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyTwoFactorLoginApiV1AuthVerify2FaPostError =
  VerifyTwoFactorLoginApiV1AuthVerify2FaPostErrors[keyof VerifyTwoFactorLoginApiV1AuthVerify2FaPostErrors];

export type VerifyTwoFactorLoginApiV1AuthVerify2FaPostResponses = {
  /**
   * Successful Response
   */
  200: LoginResponse;
};

export type VerifyTwoFactorLoginApiV1AuthVerify2FaPostResponse =
  VerifyTwoFactorLoginApiV1AuthVerify2FaPostResponses[keyof VerifyTwoFactorLoginApiV1AuthVerify2FaPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LogoutApiV1AuthLogoutPostError =
  LogoutApiV1AuthLogoutPostErrors[keyof LogoutApiV1AuthLogoutPostErrors];

export type LogoutApiV1AuthLogoutPostResponses = {
  /**
   * Response Logout Api V1 Auth Logout Post
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type LogoutApiV1AuthLogoutPostResponse =
  LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type RefreshApiV1AuthRefreshPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/refresh';
};

export type RefreshApiV1AuthRefreshPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RefreshApiV1AuthRefreshPostError =
  RefreshApiV1AuthRefreshPostErrors[keyof RefreshApiV1AuthRefreshPostErrors];

export type RefreshApiV1AuthRefreshPostResponses = {
  /**
   * Response Refresh Api V1 Auth Refresh Post
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type RefreshApiV1AuthRefreshPostResponse =
  RefreshApiV1AuthRefreshPostResponses[keyof RefreshApiV1AuthRefreshPostResponses];

export type GetCurrentUserInfoApiV1AuthMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/me';
};

export type GetCurrentUserInfoApiV1AuthMeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCurrentUserInfoApiV1AuthMeGetError =
  GetCurrentUserInfoApiV1AuthMeGetErrors[keyof GetCurrentUserInfoApiV1AuthMeGetErrors];

export type GetCurrentUserInfoApiV1AuthMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type GetCurrentUserInfoApiV1AuthMeGetResponse =
  GetCurrentUserInfoApiV1AuthMeGetResponses[keyof GetCurrentUserInfoApiV1AuthMeGetResponses];

export type VerifyEmailApiV1AuthVerifyEmailPostData = {
  body: VerifyEmailRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/verify-email';
};

export type VerifyEmailApiV1AuthVerifyEmailPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyEmailApiV1AuthVerifyEmailPostError =
  VerifyEmailApiV1AuthVerifyEmailPostErrors[keyof VerifyEmailApiV1AuthVerifyEmailPostErrors];

export type VerifyEmailApiV1AuthVerifyEmailPostResponses = {
  /**
   * Successful Response
   */
  200: VerifyEmailResponse;
};

export type VerifyEmailApiV1AuthVerifyEmailPostResponse =
  VerifyEmailApiV1AuthVerifyEmailPostResponses[keyof VerifyEmailApiV1AuthVerifyEmailPostResponses];

export type ResendVerificationApiV1AuthResendVerificationPostData = {
  body: ForgotPasswordRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/resend-verification';
};

export type ResendVerificationApiV1AuthResendVerificationPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResendVerificationApiV1AuthResendVerificationPostError =
  ResendVerificationApiV1AuthResendVerificationPostErrors[keyof ResendVerificationApiV1AuthResendVerificationPostErrors];

export type ResendVerificationApiV1AuthResendVerificationPostResponses = {
  /**
   * Response Resend Verification Api V1 Auth Resend Verification Post
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type ResendVerificationApiV1AuthResendVerificationPostResponse =
  ResendVerificationApiV1AuthResendVerificationPostResponses[keyof ResendVerificationApiV1AuthResendVerificationPostResponses];

export type ForgotPasswordApiV1AuthForgotPasswordPostData = {
  body: ForgotPasswordRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/forgot-password';
};

export type ForgotPasswordApiV1AuthForgotPasswordPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ForgotPasswordApiV1AuthForgotPasswordPostError =
  ForgotPasswordApiV1AuthForgotPasswordPostErrors[keyof ForgotPasswordApiV1AuthForgotPasswordPostErrors];

export type ForgotPasswordApiV1AuthForgotPasswordPostResponses = {
  /**
   * Response Forgot Password Api V1 Auth Forgot Password Post
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type ForgotPasswordApiV1AuthForgotPasswordPostResponse =
  ForgotPasswordApiV1AuthForgotPasswordPostResponses[keyof ForgotPasswordApiV1AuthForgotPasswordPostResponses];

export type ResetPasswordApiV1AuthResetPasswordPostData = {
  body: ResetPasswordRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/reset-password';
};

export type ResetPasswordApiV1AuthResetPasswordPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetPasswordApiV1AuthResetPasswordPostError =
  ResetPasswordApiV1AuthResetPasswordPostErrors[keyof ResetPasswordApiV1AuthResetPasswordPostErrors];

export type ResetPasswordApiV1AuthResetPasswordPostResponses = {
  /**
   * Response Reset Password Api V1 Auth Reset Password Post
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type ResetPasswordApiV1AuthResetPasswordPostResponse =
  ResetPasswordApiV1AuthResetPasswordPostResponses[keyof ResetPasswordApiV1AuthResetPasswordPostResponses];

export type ChangePasswordApiV1AuthChangePasswordPostData = {
  body: ChangePasswordRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/change-password';
};

export type ChangePasswordApiV1AuthChangePasswordPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ChangePasswordApiV1AuthChangePasswordPostError =
  ChangePasswordApiV1AuthChangePasswordPostErrors[keyof ChangePasswordApiV1AuthChangePasswordPostErrors];

export type ChangePasswordApiV1AuthChangePasswordPostResponses = {
  /**
   * Response Change Password Api V1 Auth Change Password Post
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type ChangePasswordApiV1AuthChangePasswordPostResponse =
  ChangePasswordApiV1AuthChangePasswordPostResponses[keyof ChangePasswordApiV1AuthChangePasswordPostResponses];

export type ChangeEmailApiV1AuthChangeEmailPostData = {
  body: ChangeEmailRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/change-email';
};

export type ChangeEmailApiV1AuthChangeEmailPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ChangeEmailApiV1AuthChangeEmailPostError =
  ChangeEmailApiV1AuthChangeEmailPostErrors[keyof ChangeEmailApiV1AuthChangeEmailPostErrors];

export type ChangeEmailApiV1AuthChangeEmailPostResponses = {
  /**
   * Response Change Email Api V1 Auth Change Email Post
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type ChangeEmailApiV1AuthChangeEmailPostResponse =
  ChangeEmailApiV1AuthChangeEmailPostResponses[keyof ChangeEmailApiV1AuthChangeEmailPostResponses];

export type UpdateProfileApiV1AuthProfilePutData = {
  body: ProfileUpdateRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/profile';
};

export type UpdateProfileApiV1AuthProfilePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateProfileApiV1AuthProfilePutError =
  UpdateProfileApiV1AuthProfilePutErrors[keyof UpdateProfileApiV1AuthProfilePutErrors];

export type UpdateProfileApiV1AuthProfilePutResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type UpdateProfileApiV1AuthProfilePutResponse =
  UpdateProfileApiV1AuthProfilePutResponses[keyof UpdateProfileApiV1AuthProfilePutResponses];

export type GetCurrentUserInfoApiV1UsersMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/me';
};

export type GetCurrentUserInfoApiV1UsersMeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCurrentUserInfoApiV1UsersMeGetError =
  GetCurrentUserInfoApiV1UsersMeGetErrors[keyof GetCurrentUserInfoApiV1UsersMeGetErrors];

export type GetCurrentUserInfoApiV1UsersMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type GetCurrentUserInfoApiV1UsersMeGetResponse =
  GetCurrentUserInfoApiV1UsersMeGetResponses[keyof GetCurrentUserInfoApiV1UsersMeGetResponses];

export type ListTasksApiV1TasksGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number;
    /**
     * Page Size
     *
     * Items per page
     */
    page_size?: number;
  };
  url: '/api/v1/tasks';
};

export type ListTasksApiV1TasksGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListTasksApiV1TasksGetError =
  ListTasksApiV1TasksGetErrors[keyof ListTasksApiV1TasksGetErrors];

export type ListTasksApiV1TasksGetResponses = {
  /**
   * Successful Response
   */
  200: TaskListResponse;
};

export type ListTasksApiV1TasksGetResponse =
  ListTasksApiV1TasksGetResponses[keyof ListTasksApiV1TasksGetResponses];

export type CreateTaskApiV1TasksPostData = {
  body: TaskCreate;
  path?: never;
  query?: never;
  url: '/api/v1/tasks';
};

export type CreateTaskApiV1TasksPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTaskApiV1TasksPostError =
  CreateTaskApiV1TasksPostErrors[keyof CreateTaskApiV1TasksPostErrors];

export type CreateTaskApiV1TasksPostResponses = {
  /**
   * Successful Response
   */
  201: TaskResponse;
};

export type CreateTaskApiV1TasksPostResponse =
  CreateTaskApiV1TasksPostResponses[keyof CreateTaskApiV1TasksPostResponses];

export type DeleteTaskApiV1TasksTaskIdDeleteData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: number;
  };
  query?: never;
  url: '/api/v1/tasks/{task_id}';
};

export type DeleteTaskApiV1TasksTaskIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTaskApiV1TasksTaskIdDeleteError =
  DeleteTaskApiV1TasksTaskIdDeleteErrors[keyof DeleteTaskApiV1TasksTaskIdDeleteErrors];

export type DeleteTaskApiV1TasksTaskIdDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTaskApiV1TasksTaskIdDeleteResponse =
  DeleteTaskApiV1TasksTaskIdDeleteResponses[keyof DeleteTaskApiV1TasksTaskIdDeleteResponses];

export type GetTaskApiV1TasksTaskIdGetData = {
  body?: never;
  path: {
    /**
     * Task Id
     */
    task_id: number;
  };
  query?: never;
  url: '/api/v1/tasks/{task_id}';
};

export type GetTaskApiV1TasksTaskIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTaskApiV1TasksTaskIdGetError =
  GetTaskApiV1TasksTaskIdGetErrors[keyof GetTaskApiV1TasksTaskIdGetErrors];

export type GetTaskApiV1TasksTaskIdGetResponses = {
  /**
   * Successful Response
   */
  200: TaskResponse;
};

export type GetTaskApiV1TasksTaskIdGetResponse =
  GetTaskApiV1TasksTaskIdGetResponses[keyof GetTaskApiV1TasksTaskIdGetResponses];

export type UpdateTaskApiV1TasksTaskIdPatchData = {
  body: TaskUpdate;
  path: {
    /**
     * Task Id
     */
    task_id: number;
  };
  query?: never;
  url: '/api/v1/tasks/{task_id}';
};

export type UpdateTaskApiV1TasksTaskIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTaskApiV1TasksTaskIdPatchError =
  UpdateTaskApiV1TasksTaskIdPatchErrors[keyof UpdateTaskApiV1TasksTaskIdPatchErrors];

export type UpdateTaskApiV1TasksTaskIdPatchResponses = {
  /**
   * Successful Response
   */
  200: TaskResponse;
};

export type UpdateTaskApiV1TasksTaskIdPatchResponse =
  UpdateTaskApiV1TasksTaskIdPatchResponses[keyof UpdateTaskApiV1TasksTaskIdPatchResponses];

export type GetTwoFactorStatusApiV1TwoFactorStatusGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/two-factor/status';
};

export type GetTwoFactorStatusApiV1TwoFactorStatusGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTwoFactorStatusApiV1TwoFactorStatusGetError =
  GetTwoFactorStatusApiV1TwoFactorStatusGetErrors[keyof GetTwoFactorStatusApiV1TwoFactorStatusGetErrors];

export type GetTwoFactorStatusApiV1TwoFactorStatusGetResponses = {
  /**
   * Successful Response
   */
  200: TwoFactorStatusResponse;
};

export type GetTwoFactorStatusApiV1TwoFactorStatusGetResponse =
  GetTwoFactorStatusApiV1TwoFactorStatusGetResponses[keyof GetTwoFactorStatusApiV1TwoFactorStatusGetResponses];

export type SetupTwoFactorApiV1TwoFactorSetupPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/two-factor/setup';
};

export type SetupTwoFactorApiV1TwoFactorSetupPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SetupTwoFactorApiV1TwoFactorSetupPostError =
  SetupTwoFactorApiV1TwoFactorSetupPostErrors[keyof SetupTwoFactorApiV1TwoFactorSetupPostErrors];

export type SetupTwoFactorApiV1TwoFactorSetupPostResponses = {
  /**
   * Successful Response
   */
  200: TwoFactorSetupResponse;
};

export type SetupTwoFactorApiV1TwoFactorSetupPostResponse =
  SetupTwoFactorApiV1TwoFactorSetupPostResponses[keyof SetupTwoFactorApiV1TwoFactorSetupPostResponses];

export type EnableTwoFactorApiV1TwoFactorEnablePostData = {
  body: TwoFactorEnableRequest;
  path?: never;
  query?: never;
  url: '/api/v1/two-factor/enable';
};

export type EnableTwoFactorApiV1TwoFactorEnablePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EnableTwoFactorApiV1TwoFactorEnablePostError =
  EnableTwoFactorApiV1TwoFactorEnablePostErrors[keyof EnableTwoFactorApiV1TwoFactorEnablePostErrors];

export type EnableTwoFactorApiV1TwoFactorEnablePostResponses = {
  /**
   * Successful Response
   */
  200: TwoFactorEnableResponse;
};

export type EnableTwoFactorApiV1TwoFactorEnablePostResponse =
  EnableTwoFactorApiV1TwoFactorEnablePostResponses[keyof EnableTwoFactorApiV1TwoFactorEnablePostResponses];

export type DisableTwoFactorApiV1TwoFactorDisablePostData = {
  body: TwoFactorDisableRequest;
  path?: never;
  query?: never;
  url: '/api/v1/two-factor/disable';
};

export type DisableTwoFactorApiV1TwoFactorDisablePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DisableTwoFactorApiV1TwoFactorDisablePostError =
  DisableTwoFactorApiV1TwoFactorDisablePostErrors[keyof DisableTwoFactorApiV1TwoFactorDisablePostErrors];

export type DisableTwoFactorApiV1TwoFactorDisablePostResponses = {
  /**
   * Response Disable Two Factor Api V1 Two Factor Disable Post
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type DisableTwoFactorApiV1TwoFactorDisablePostResponse =
  DisableTwoFactorApiV1TwoFactorDisablePostResponses[keyof DisableTwoFactorApiV1TwoFactorDisablePostResponses];

export type VerifyTwoFactorApiV1TwoFactorVerifyPostData = {
  body: TwoFactorVerifyRequest;
  path?: never;
  query?: never;
  url: '/api/v1/two-factor/verify';
};

export type VerifyTwoFactorApiV1TwoFactorVerifyPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyTwoFactorApiV1TwoFactorVerifyPostError =
  VerifyTwoFactorApiV1TwoFactorVerifyPostErrors[keyof VerifyTwoFactorApiV1TwoFactorVerifyPostErrors];

export type VerifyTwoFactorApiV1TwoFactorVerifyPostResponses = {
  /**
   * Successful Response
   */
  200: TwoFactorVerifyResponse;
};

export type VerifyTwoFactorApiV1TwoFactorVerifyPostResponse =
  VerifyTwoFactorApiV1TwoFactorVerifyPostResponses[keyof VerifyTwoFactorApiV1TwoFactorVerifyPostResponses];

export type RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostData = {
  body: RegenerateBackupCodesRequest;
  path?: never;
  query?: never;
  url: '/api/v1/two-factor/regenerate-backup-codes';
};

export type RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostError =
  RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostErrors[keyof RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostErrors];

export type RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostResponses = {
  /**
   * Successful Response
   */
  200: RegenerateBackupCodesResponse;
};

export type RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostResponse =
  RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostResponses[keyof RegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostResponses];

export type GetOauthProvidersApiV1OauthProvidersGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/oauth/providers';
};

export type GetOauthProvidersApiV1OauthProvidersGetResponses = {
  /**
   * Response Get Oauth Providers Api V1 Oauth Providers Get
   *
   * Successful Response
   */
  200: {
    [key: string]: boolean;
  };
};

export type GetOauthProvidersApiV1OauthProvidersGetResponse =
  GetOauthProvidersApiV1OauthProvidersGetResponses[keyof GetOauthProvidersApiV1OauthProvidersGetResponses];

export type OauthAuthorizeApiV1OauthProviderAuthorizeGetData = {
  body?: never;
  path: {
    /**
     * Provider
     */
    provider: string;
  };
  query?: {
    /**
     * Redirect Url
     */
    redirect_url?: string | null;
  };
  url: '/api/v1/oauth/{provider}/authorize';
};

export type OauthAuthorizeApiV1OauthProviderAuthorizeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OauthAuthorizeApiV1OauthProviderAuthorizeGetError =
  OauthAuthorizeApiV1OauthProviderAuthorizeGetErrors[keyof OauthAuthorizeApiV1OauthProviderAuthorizeGetErrors];

export type OauthAuthorizeApiV1OauthProviderAuthorizeGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OauthAuthorizeLinkApiV1OauthProviderAuthorizeLinkGetData = {
  body?: never;
  path: {
    /**
     * Provider
     */
    provider: string;
  };
  query?: {
    /**
     * Redirect Url
     */
    redirect_url?: string | null;
  };
  url: '/api/v1/oauth/{provider}/authorize/link';
};

export type OauthAuthorizeLinkApiV1OauthProviderAuthorizeLinkGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OauthAuthorizeLinkApiV1OauthProviderAuthorizeLinkGetError =
  OauthAuthorizeLinkApiV1OauthProviderAuthorizeLinkGetErrors[keyof OauthAuthorizeLinkApiV1OauthProviderAuthorizeLinkGetErrors];

export type OauthAuthorizeLinkApiV1OauthProviderAuthorizeLinkGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type OauthCallbackApiV1OauthProviderCallbackGetData = {
  body?: never;
  path: {
    /**
     * Provider
     */
    provider: string;
  };
  query: {
    /**
     * Code
     */
    code: string;
    /**
     * State
     */
    state: string;
  };
  url: '/api/v1/oauth/{provider}/callback';
};

export type OauthCallbackApiV1OauthProviderCallbackGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type OauthCallbackApiV1OauthProviderCallbackGetError =
  OauthCallbackApiV1OauthProviderCallbackGetErrors[keyof OauthCallbackApiV1OauthProviderCallbackGetErrors];

export type OauthCallbackApiV1OauthProviderCallbackGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetConnectedAccountsApiV1OauthAccountsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/oauth/accounts';
};

export type GetConnectedAccountsApiV1OauthAccountsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetConnectedAccountsApiV1OauthAccountsGetError =
  GetConnectedAccountsApiV1OauthAccountsGetErrors[keyof GetConnectedAccountsApiV1OauthAccountsGetErrors];

export type GetConnectedAccountsApiV1OauthAccountsGetResponses = {
  /**
   * Successful Response
   */
  200: ConnectedAccountsResponse;
};

export type GetConnectedAccountsApiV1OauthAccountsGetResponse =
  GetConnectedAccountsApiV1OauthAccountsGetResponses[keyof GetConnectedAccountsApiV1OauthAccountsGetResponses];

export type UnlinkOauthAccountApiV1OauthProviderUnlinkDeleteData = {
  body?: never;
  path: {
    /**
     * Provider
     */
    provider: string;
  };
  query?: never;
  url: '/api/v1/oauth/{provider}/unlink';
};

export type UnlinkOauthAccountApiV1OauthProviderUnlinkDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UnlinkOauthAccountApiV1OauthProviderUnlinkDeleteError =
  UnlinkOauthAccountApiV1OauthProviderUnlinkDeleteErrors[keyof UnlinkOauthAccountApiV1OauthProviderUnlinkDeleteErrors];

export type UnlinkOauthAccountApiV1OauthProviderUnlinkDeleteResponses = {
  /**
   * Response Unlink Oauth Account Api V1 Oauth  Provider  Unlink Delete
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type UnlinkOauthAccountApiV1OauthProviderUnlinkDeleteResponse =
  UnlinkOauthAccountApiV1OauthProviderUnlinkDeleteResponses[keyof UnlinkOauthAccountApiV1OauthProviderUnlinkDeleteResponses];

export type SendTestEmailApiV1TestSendTestEmailPostData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Recipient Email
     */
    recipient_email: string;
  };
  url: '/api/v1/test/send-test-email';
};

export type SendTestEmailApiV1TestSendTestEmailPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SendTestEmailApiV1TestSendTestEmailPostError =
  SendTestEmailApiV1TestSendTestEmailPostErrors[keyof SendTestEmailApiV1TestSendTestEmailPostErrors];

export type SendTestEmailApiV1TestSendTestEmailPostResponses = {
  /**
   * Response Send Test Email Api V1 Test Send Test Email Post
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type SendTestEmailApiV1TestSendTestEmailPostResponse =
  SendTestEmailApiV1TestSendTestEmailPostResponses[keyof SendTestEmailApiV1TestSendTestEmailPostResponses];
