// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * ChangeEmailRequest
 *
 * Request to change email for authenticated user.
 */
export const zChangeEmailRequest = z.object({
  new_email: z.email(),
  password: z.string(),
});

/**
 * ChangePasswordRequest
 *
 * Request to change password for authenticated user.
 */
export const zChangePasswordRequest = z.object({
  current_password: z.string(),
  new_password: z.string(),
});

/**
 * ForgotPasswordRequest
 *
 * Request to initiate password reset.
 */
export const zForgotPasswordRequest = z.object({
  email: z.email(),
});

/**
 * OAuthAccountResponse
 *
 * Response for a linked OAuth account.
 */
export const zOAuthAccountResponse = z.object({
  provider: z.string(),
  provider_user_id: z.string(),
  email: z.optional(z.union([z.string(), z.null()])),
  name: z.optional(z.union([z.string(), z.null()])),
  avatar_url: z.optional(z.union([z.string(), z.null()])),
  connected_at: z.string(),
});

/**
 * ConnectedAccountsResponse
 *
 * Response for listing connected accounts.
 */
export const zConnectedAccountsResponse = z.object({
  accounts: z.array(zOAuthAccountResponse),
});

/**
 * OAuthCallbackRequest
 *
 * Request body for OAuth callback.
 */
export const zOAuthCallbackRequest = z.object({
  code: z.string(),
  state: z.string(),
});

/**
 * RegenerateBackupCodesRequest
 *
 * Request to regenerate backup codes.
 */
export const zRegenerateBackupCodesRequest = z.object({
  password: z.string(),
});

/**
 * RegenerateBackupCodesResponse
 *
 * Response for backup code regeneration.
 */
export const zRegenerateBackupCodesResponse = z.object({
  backup_codes: z.array(z.string()),
});

/**
 * ResetPasswordRequest
 *
 * Request to reset password with token.
 */
export const zResetPasswordRequest = z.object({
  token: z.string(),
  password: z.string(),
});

/**
 * TaskPriority
 *
 * Enum representing the priority of a task.
 */
export const zTaskPriority = z.enum(['low', 'medium', 'high', 'urgent']);

/**
 * TaskCreate
 *
 * Schema for creating a new task.
 */
export const zTaskCreate = z.object({
  title: z.string().min(1).max(255),
  description: z.string().min(1),
  priority: z.optional(zTaskPriority).default('medium'),
  repository_id: z.optional(z.union([z.int(), z.null()])),
});

/**
 * TaskStatus
 *
 * Enum representing the status of a task.
 */
export const zTaskStatus = z.enum([
  'pending',
  'planning',
  'in_progress',
  'testing',
  'reviewing',
  'completed',
  'failed',
  'cancelled',
]);

/**
 * TaskResponse
 *
 * Schema for task responses.
 */
export const zTaskResponse = z.object({
  title: z.string().min(1).max(255),
  description: z.string().min(1),
  priority: z.optional(zTaskPriority).default('medium'),
  id: z.int(),
  status: zTaskStatus,
  user_id: z.int(),
  repository_id: z.union([z.int(), z.null()]),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
});

/**
 * TaskListResponse
 *
 * Schema for paginated task list responses.
 */
export const zTaskListResponse = z.object({
  items: z.array(zTaskResponse),
  total: z.int(),
  page: z.int(),
  page_size: z.int(),
});

/**
 * TaskUpdate
 *
 * Schema for updating a task.
 */
export const zTaskUpdate = z.object({
  title: z.optional(z.union([z.string().min(1).max(255), z.null()])),
  description: z.optional(z.union([z.string().min(1), z.null()])),
  status: z.optional(z.union([zTaskStatus, z.null()])),
  priority: z.optional(z.union([zTaskPriority, z.null()])),
  repository_id: z.optional(z.union([z.int(), z.null()])),
});

/**
 * TokenResponse
 *
 * Schema for authentication token response.
 */
export const zTokenResponse = z.object({
  access_token: z.string(),
  refresh_token: z.string(),
  token_type: z.optional(z.string()).default('bearer'),
});

/**
 * TwoFactorDisableRequest
 *
 * Request to disable 2FA.
 */
export const zTwoFactorDisableRequest = z.object({
  password: z.string(),
});

/**
 * TwoFactorEnableRequest
 *
 * Request to enable 2FA.
 */
export const zTwoFactorEnableRequest = z.object({
  code: z.string(),
});

/**
 * TwoFactorEnableResponse
 *
 * Response for enabling 2FA.
 */
export const zTwoFactorEnableResponse = z.object({
  backup_codes: z.array(z.string()),
});

/**
 * TwoFactorSetupResponse
 *
 * Response for 2FA setup initiation.
 */
export const zTwoFactorSetupResponse = z.object({
  qr_code: z.string(),
  secret: z.string(),
});

/**
 * TwoFactorStatusResponse
 *
 * Response for 2FA status check.
 */
export const zTwoFactorStatusResponse = z.object({
  enabled: z.boolean(),
  backup_codes_remaining: z.optional(z.union([z.int(), z.null()])),
});

/**
 * TwoFactorVerifyRequest
 *
 * Request to verify a 2FA code.
 */
export const zTwoFactorVerifyRequest = z.object({
  code: z.string(),
});

/**
 * TwoFactorVerifyResponse
 *
 * Response for 2FA verification.
 */
export const zTwoFactorVerifyResponse = z.object({
  valid: z.boolean(),
});

/**
 * UserCreate
 *
 * Schema for creating a new user.
 */
export const zUserCreate = z.object({
  email: z.email(),
  password: z.string().min(8),
});

/**
 * UserLogin
 *
 * Schema for user login.
 */
export const zUserLogin = z.object({
  email: z.email(),
  password: z.string(),
});

/**
 * UserResponse
 *
 * Schema for user responses.
 */
export const zUserResponse = z.object({
  email: z.email(),
  id: z.int(),
  is_active: z.boolean(),
  is_superuser: z.boolean(),
  email_verified: z.boolean(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
});

/**
 * LoginResponse
 *
 * Response for successful login.
 */
export const zLoginResponse = z.object({
  message: z.string(),
  user: zUserResponse,
  email_verified: z.boolean(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.optional(z.array(zValidationError)),
});

/**
 * VerifyEmailRequest
 *
 * Request to verify email with token.
 */
export const zVerifyEmailRequest = z.object({
  token: z.string(),
});

export const zHealthCheckHealthGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Health Check Health Get
 *
 * Successful Response
 */
export const zHealthCheckHealthGetResponse = z.record(z.string(), z.string());

export const zRegisterUserApiV1AuthRegisterPostData = z.object({
  body: zUserCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterUserApiV1AuthRegisterPostResponse = zUserResponse;

export const zLoginUserApiV1AuthLoginPostData = z.object({
  body: zUserLogin,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zLoginUserApiV1AuthLoginPostResponse = zTokenResponse;

export const zLogoutApiV1AuthLogoutPostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Logout Api V1 Auth Logout Post
 *
 * Successful Response
 */
export const zLogoutApiV1AuthLogoutPostResponse = z.record(z.string(), z.string());

export const zRefreshApiV1AuthRefreshPostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Refresh Api V1 Auth Refresh Post
 *
 * Successful Response
 */
export const zRefreshApiV1AuthRefreshPostResponse = z.record(z.string(), z.string());

export const zGetCurrentUserInfoApiV1AuthMeGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetCurrentUserInfoApiV1AuthMeGetResponse = zUserResponse;

export const zVerifyEmailApiV1AuthVerifyEmailPostData = z.object({
  body: zVerifyEmailRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Verify Email Api V1 Auth Verify Email Post
 *
 * Successful Response
 */
export const zVerifyEmailApiV1AuthVerifyEmailPostResponse = z.record(z.string(), z.string());

export const zResendVerificationApiV1AuthResendVerificationPostData = z.object({
  body: zForgotPasswordRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Resend Verification Api V1 Auth Resend Verification Post
 *
 * Successful Response
 */
export const zResendVerificationApiV1AuthResendVerificationPostResponse = z.record(
  z.string(),
  z.string()
);

export const zForgotPasswordApiV1AuthForgotPasswordPostData = z.object({
  body: zForgotPasswordRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Forgot Password Api V1 Auth Forgot Password Post
 *
 * Successful Response
 */
export const zForgotPasswordApiV1AuthForgotPasswordPostResponse = z.record(z.string(), z.string());

export const zResetPasswordApiV1AuthResetPasswordPostData = z.object({
  body: zResetPasswordRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Reset Password Api V1 Auth Reset Password Post
 *
 * Successful Response
 */
export const zResetPasswordApiV1AuthResetPasswordPostResponse = z.record(z.string(), z.string());

export const zChangePasswordApiV1AuthChangePasswordPostData = z.object({
  body: zChangePasswordRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Change Password Api V1 Auth Change Password Post
 *
 * Successful Response
 */
export const zChangePasswordApiV1AuthChangePasswordPostResponse = z.record(z.string(), z.string());

export const zChangeEmailApiV1AuthChangeEmailPostData = z.object({
  body: zChangeEmailRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Change Email Api V1 Auth Change Email Post
 *
 * Successful Response
 */
export const zChangeEmailApiV1AuthChangeEmailPostResponse = z.record(z.string(), z.string());

export const zGetCurrentUserInfoApiV1UsersMeGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetCurrentUserInfoApiV1UsersMeGetResponse = zUserResponse;

export const zListTasksApiV1TasksGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.int().gte(1)).default(1),
      page_size: z.optional(z.int().gte(1).lte(100)).default(50),
    })
  ),
});

/**
 * Successful Response
 */
export const zListTasksApiV1TasksGetResponse = zTaskListResponse;

export const zCreateTaskApiV1TasksPostData = z.object({
  body: zTaskCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zCreateTaskApiV1TasksPostResponse = zTaskResponse;

export const zDeleteTaskApiV1TasksTaskIdDeleteData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    task_id: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zDeleteTaskApiV1TasksTaskIdDeleteResponse = z.void();

export const zGetTaskApiV1TasksTaskIdGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    task_id: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetTaskApiV1TasksTaskIdGetResponse = zTaskResponse;

export const zUpdateTaskApiV1TasksTaskIdPatchData = z.object({
  body: zTaskUpdate,
  path: z.object({
    task_id: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zUpdateTaskApiV1TasksTaskIdPatchResponse = zTaskResponse;

export const zGetTwoFactorStatusApiV1TwoFactorStatusGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetTwoFactorStatusApiV1TwoFactorStatusGetResponse = zTwoFactorStatusResponse;

export const zSetupTwoFactorApiV1TwoFactorSetupPostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zSetupTwoFactorApiV1TwoFactorSetupPostResponse = zTwoFactorSetupResponse;

export const zEnableTwoFactorApiV1TwoFactorEnablePostData = z.object({
  body: zTwoFactorEnableRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zEnableTwoFactorApiV1TwoFactorEnablePostResponse = zTwoFactorEnableResponse;

export const zDisableTwoFactorApiV1TwoFactorDisablePostData = z.object({
  body: zTwoFactorDisableRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Disable Two Factor Api V1 Two Factor Disable Post
 *
 * Successful Response
 */
export const zDisableTwoFactorApiV1TwoFactorDisablePostResponse = z.record(z.string(), z.string());

export const zVerifyTwoFactorApiV1TwoFactorVerifyPostData = z.object({
  body: zTwoFactorVerifyRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zVerifyTwoFactorApiV1TwoFactorVerifyPostResponse = zTwoFactorVerifyResponse;

export const zRegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostData = z.object({
  body: zRegenerateBackupCodesRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegenerateBackupCodesApiV1TwoFactorRegenerateBackupCodesPostResponse =
  zRegenerateBackupCodesResponse;

export const zGetOauthProvidersApiV1OauthProvidersGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Get Oauth Providers Api V1 Oauth Providers Get
 *
 * Successful Response
 */
export const zGetOauthProvidersApiV1OauthProvidersGetResponse = z.record(z.string(), z.boolean());

export const zOauthAuthorizeApiV1OauthProviderAuthorizeGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    provider: z.string(),
  }),
  query: z.optional(
    z.object({
      redirect_url: z.optional(z.union([z.string(), z.null()])),
    })
  ),
});

export const zOauthAuthorizeLinkApiV1OauthProviderAuthorizeLinkGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    provider: z.string(),
  }),
  query: z.optional(
    z.object({
      redirect_url: z.optional(z.union([z.string(), z.null()])),
    })
  ),
});

export const zOauthCallbackApiV1OauthProviderCallbackPostData = z.object({
  body: zOAuthCallbackRequest,
  path: z.object({
    provider: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * Response Oauth Callback Api V1 Oauth  Provider  Callback Post
 *
 * Successful Response
 */
export const zOauthCallbackApiV1OauthProviderCallbackPostResponse = z.record(
  z.string(),
  z.unknown()
);

export const zGetConnectedAccountsApiV1OauthAccountsGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetConnectedAccountsApiV1OauthAccountsGetResponse = zConnectedAccountsResponse;

export const zUnlinkOauthAccountApiV1OauthProviderUnlinkDeleteData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    provider: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * Response Unlink Oauth Account Api V1 Oauth  Provider  Unlink Delete
 *
 * Successful Response
 */
export const zUnlinkOauthAccountApiV1OauthProviderUnlinkDeleteResponse = z.record(
  z.string(),
  z.string()
);

export const zSendTestEmailApiV1TestSendTestEmailPostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    recipient_email: z.string(),
  }),
});

/**
 * Response Send Test Email Api V1 Test Send Test Email Post
 *
 * Successful Response
 */
export const zSendTestEmailApiV1TestSendTestEmailPostResponse = z.record(z.string(), z.string());
