// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * TaskPriority
 *
 * Enum representing the priority of a task.
 */
export const zTaskPriority = z.enum(['low', 'medium', 'high', 'urgent']);

/**
 * TaskCreate
 *
 * Schema for creating a new task.
 */
export const zTaskCreate = z.object({
  title: z.string().min(1).max(255),
  description: z.string().min(1),
  priority: z.optional(zTaskPriority).default('medium'),
  repository_id: z.optional(z.union([z.int(), z.null()])),
});

/**
 * TaskStatus
 *
 * Enum representing the status of a task.
 */
export const zTaskStatus = z.enum([
  'pending',
  'planning',
  'in_progress',
  'testing',
  'reviewing',
  'completed',
  'failed',
  'cancelled',
]);

/**
 * TaskResponse
 *
 * Schema for task responses.
 */
export const zTaskResponse = z.object({
  title: z.string().min(1).max(255),
  description: z.string().min(1),
  priority: z.optional(zTaskPriority).default('medium'),
  id: z.int(),
  status: zTaskStatus,
  user_id: z.int(),
  repository_id: z.union([z.int(), z.null()]),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
});

/**
 * TaskListResponse
 *
 * Schema for paginated task list responses.
 */
export const zTaskListResponse = z.object({
  items: z.array(zTaskResponse),
  total: z.int(),
  page: z.int(),
  page_size: z.int(),
});

/**
 * TaskUpdate
 *
 * Schema for updating a task.
 */
export const zTaskUpdate = z.object({
  title: z.optional(z.union([z.string().min(1).max(255), z.null()])),
  description: z.optional(z.union([z.string().min(1), z.null()])),
  status: z.optional(z.union([zTaskStatus, z.null()])),
  priority: z.optional(z.union([zTaskPriority, z.null()])),
  repository_id: z.optional(z.union([z.int(), z.null()])),
});

/**
 * TokenResponse
 *
 * Schema for authentication token response.
 */
export const zTokenResponse = z.object({
  access_token: z.string(),
  refresh_token: z.string(),
  token_type: z.optional(z.string()).default('bearer'),
});

/**
 * UserCreate
 *
 * Schema for creating a new user.
 */
export const zUserCreate = z.object({
  email: z.email(),
  password: z.string().min(8),
});

/**
 * UserLogin
 *
 * Schema for user login.
 */
export const zUserLogin = z.object({
  email: z.email(),
  password: z.string(),
});

/**
 * UserResponse
 *
 * Schema for user responses.
 */
export const zUserResponse = z.object({
  email: z.email(),
  id: z.int(),
  is_active: z.boolean(),
  is_superuser: z.boolean(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.optional(z.array(zValidationError)),
});

export const zHealthCheckHealthGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Health Check Health Get
 *
 * Successful Response
 */
export const zHealthCheckHealthGetResponse = z.record(z.string(), z.string());

export const zRegisterUserApiV1AuthRegisterPostData = z.object({
  body: zUserCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterUserApiV1AuthRegisterPostResponse = zUserResponse;

export const zLoginUserApiV1AuthLoginPostData = z.object({
  body: zUserLogin,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zLoginUserApiV1AuthLoginPostResponse = zTokenResponse;

export const zGetCurrentUserInfoApiV1UsersMeGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetCurrentUserInfoApiV1UsersMeGetResponse = zUserResponse;

export const zListTasksApiV1TasksGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.int().gte(1)).default(1),
      page_size: z.optional(z.int().gte(1).lte(100)).default(50),
    })
  ),
});

/**
 * Successful Response
 */
export const zListTasksApiV1TasksGetResponse = zTaskListResponse;

export const zCreateTaskApiV1TasksPostData = z.object({
  body: zTaskCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zCreateTaskApiV1TasksPostResponse = zTaskResponse;

export const zDeleteTaskApiV1TasksTaskIdDeleteData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    task_id: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zDeleteTaskApiV1TasksTaskIdDeleteResponse = z.void();

export const zGetTaskApiV1TasksTaskIdGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    task_id: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetTaskApiV1TasksTaskIdGetResponse = zTaskResponse;

export const zUpdateTaskApiV1TasksTaskIdPatchData = z.object({
  body: zTaskUpdate,
  path: z.object({
    task_id: z.int(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zUpdateTaskApiV1TasksTaskIdPatchResponse = zTaskResponse;
