- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "documentation"
  color: "0075ca"
  description: "Documentation improvements"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue already exists"
- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"
- name: "priority: critical"
  color: "b60205"
  description: "Must be fixed immediately"
- name: "priority: high"
  color: "d93f0b"
  description: "Important for next release"
- name: "priority: medium"
  color: "fbca04"
  description: "Should be done soon"
- name: "priority: low"
  color: "0e8a16"
  description: "Nice to have"
- name: "type: backend"
  color: "1d76db"
  description: "Backend related"
- name: "type: frontend"
  color: "5319e7"
  description: "Frontend related"
- name: "type: agents"
  color: "f9d0c4"
  description: "Agent/LLM related"
- name: "type: infrastructure"
  color: "bfdadc"
  description: "Docker/CI/CD related"
- name: "status: in progress"
  color: "ffeb3b"
  description: "Currently being worked on"
- name: "status: blocked"
  color: "ff5722"
  description: "Blocked by something"
- name: "status: needs review"
  color: "03a9f4"
  description: "Needs code review"
- name: "dependencies"
  color: "0366d6"
  description: "Dependency updates"